/**
 * CHANGELOG — WraeclastLedger
 * Add new entries at the TOP. The "What's New" banner shows entries ≥ current version.
 */
export interface ChangelogEntry {
  version: string;
  date: string;
  changes: string[];
}

export const CHANGELOG: ChangelogEntry[] = [
  {
    version: '1.0.54',
    date: '2026-04-26',
    changes: [
      'Atlas Calc: wizard no longer skips when a blank pathofpathing tree is loaded — pathofpathing emits a hash even for an empty tree which was incorrectly treated as configured',
      'Atlas Calc: wizard visibility now derived purely from actual calc settings (mounting, fragments, nodes) and the dismissed flag',
      'Atlas Calc: wizard resets correctly on every New Session — dismissed flag cleared, step back to mounting',
      'Atlas Calc: pill editing state clears automatically when settings are applied externally (Load Build Settings)',
      'Atlas Calc: added Skip button with tooltip — skips wizard and shows pills immediately',
      'Atlas Tree: New Session no longer triggers stat reading or leaves the stats panel open',
    ],
  },
  {
    version: '1.0.53',
    date: '2026-04-26',
    changes: [
      'Strategy Browser: group/party play support — solo is the default assumption, no tag needed',
      'Share modal: Party Play toggle — when enabled adds "👥 Party Play: Yes" to the export',
      'Strategy Browser: group strategies show a 👥 cyan badge next to the author name with tooltip',
      'Strategy Browser: 👥 filter toggle in the filter row — click to hide group play strategies and see solo-only',
      'Parser: Party Play: Yes detected from raw_export for backward compatibility with existing strategies',
      'Server: is_group_play column added to strategies table — requires a one-time database migration',
    ],
  },
  {
    version: '1.0.52',
    date: '2026-04-26',
    changes: [
      'Brick exclusions: fixed 6 broken/suboptimal regexTerms in BRICK_MOD_DEFS',
      'triple → oral (Triple Curse — "triple" matched nothing in any map mod text)',
      'ess def → fenc (Less Defences — "ess def" never appears in the mod text)',
      'o al → ax R (Reduced Max Res — o al hit Afflicting/Conflagrating)',
      'ossesse → poss (Possessed), uffs on → yers e (Buffs Expire), enetr → net (Penetrates)',
      'Map Analyzer: mod detection now uses multi-line keyword matching — mods with 2+ effect lines are now correctly identified',
      'Map Analyzer: complete uber + top-tier mod pools from authoritative JSON sources',
    ],
  },
  {
    version: '1.0.51',
    date: '2026-04-25',
    changes: [
      'Fixed: ax R replaces all m (Max Res) — all m was matching Afflicting+Conflagrating ("All Monster Damage"); ax R from m**ax R**esistances is unique',
      'Fixed: ter Mo replaces veme (Fleet) — veme was matching Juggernaut+Unstoppable ("Monsters\u2019 Movement Speed"); ter Mo requires space-before-M which Monsters\u2019 (apostrophe) never provides',
      'uberMapMods.ts: fully rewritten from authoritative uber_tier.json — all mods present, all effect lines complete, correct bonuses',
      'regularMapMods.ts: fully rewritten from authoritative top_tier.json — complete mod pool with all effect lines that were previously missing',
      'Both mod files now have verified regexToken fields where applicable',
    ],
  },
  {
    version: '1.0.50',
    date: '2026-04-25',
    changes: [
      'Fixed: all m replaces -20 (Max Res both groups) — -20 was matching top tier "-20% to amount of Suppressed Spell Damage Prevented"; "all m" from "to all maximum" avoids this',
      'Fixed: veme replaces eme (Fleet/Movement) — eme matched anything containing "Elemental" (12 overlaps); "Elemental" has no v so "veme" from "movement" is clean',
      'Fixed: oral replaces mpor (Triple Curse) — mpor matched "Temporarily Revive" ("Tempora**r**ily"); "oral" from "Temp**oral** Chains" is distinct (r vs l at position 4)',
      'Fixed: a Ma replaces gy S (Extra ES) — gy S matched any mod with Energy Shield text (5 overlaps); only "Extra Maximum" contains the sequence a-space-M-a',
      'Fixed: m End replaces dura (Endurance Charges) — dura matched Poison Duration + top-tier Endurance mods; "m End" from "Maximum End**urance" avoids "Maximum Ene**rgy" (e not d)',
    ],
  },
  {
    version: '1.0.49',
    date: '2026-04-25',
    changes: [
      'Regex Builder: full collision audit against both uber AND top-tier originator mod pools',
      'Fixed: -t replaces hap (Shaper-Touched, saves 1 char)',
      'Fixed: -20 replaces o al (Max Res, both occurrences — uniquely targets -20% uber vs -12 to -9% top tier)',
      'Fixed: deb replaces xpi (of Defiance — xpi was also matching Buffs on Players expire)',
      'Fixed: k d replaces k a (Stalwart — k a collided with Attack and Cast Speed)',
      'Fixed: t 20 replaces f p (Punishing — reflects 20% vs top tier 18%, now unique)',
      'Fixed: eme replaces nt s (Fleet — nt s was matching Juggernaut Action Speed line; eme from movement is not in Action Speed)',
      'Fixed: az replaces nth (Labyrinth — nth collided with Synthetic/Synthesis Boss top tier)',
      'Fixed: n ig replaces nite (Afflicting — n ig from can ignite vs top tier chance to/always ignites)',
      'Fixed: mpor replaces uln (Triple Curse — Temporal Chains is unique to uber; top tier only has Vulnerability)',
      'Fixed: gy S replaces as Ex (Extra ES — as Ex matched Extra Chaos and Extra Elemental too)',
      'Fixed: mum f replaces renzy (Frenzy Charges — renzy matched of Enervation steals-charges mod)',
      'Fixed: dura replaces mum e (Endurance — mum e collided with Maximum Energy Shield)',
      'Noted: tun, poss, 2 a, ter D, yers e, o su, uct have unavoidable top-tier overlaps (same mod text, different stats)',
    ],
  },
  {
    version: '1.0.48',
    date: '2026-04-25',
    changes: [
      'Regex Builder: 5 more token compressions — 2 a (AoE), oss (Possessed), net (Penetrates), uct (PDR), um p (Power Charges)',
      'Regex Builder: tooltips now dark-themed with border, matching app aesthetic; token shown as bold monospace pill; no redundant label repetition',
      'Regex Builder: \'At least X\' control bar given distinct dark green background to visually separate from mod list above it',
      'Regex Builder: per-group regex preview now in a distinct dark inset block',
      'Regex Builder: \'How this works\' collapsed by default — click to expand; power users know it, first-timers can discover it',
      'Regex Builder: \'Giga currency\' renamed to \'Currency Floor (Ignore Pack Size)\' for clarity',
    ],
  },
  {
    version: '1.0.47',
    date: '2026-04-24',
    changes: [
      'Regex Builder: maximum token compression pass — all tokens reduced to absolute minimum unique length',
      'Saves up to 3-5 chars per token, enabling significantly more complex K-of-N combinations before hitting 250-char limit',
      'lid(3) chain, ssed(4) possessed, rea o(5) AoE, ter D(5) monster damage, nt s(4) speed, o al(4) max res, enet(4) penetrates',
      'nite(4) ignite/freeze, vol(3) volatile, uln(3) vulnerability, fenc(4) defences, rasp(4) grasping, as Ex(5) extra ES',
      'o su(4) suppress, duct(4) reduction, mum p(5) power charges',
      'xpi(3) expire, k a(3) block attack, f p(3) reflect phys, tun(3) stunned, eor(3) meteor',
    ],
  },
  {
    version: '1.0.46',
    date: '2026-04-24',
    changes: [
      'Regex Builder: all mod groups now start with nothing selected — click to pick your mods',
      'Regex Builder: Regex Builder tab added to default layout next to Regex (users with saved layouts can drag it there manually or reset layout to default)',
      'Regex Builder: Shaper-Touched tooltip cleaned up',
      'Regex Builder: applied research SUS token improvements — mav (3), nth (3), rke (3), ne b (4), vola (4), teor (4), et sp (5), yers e (6) replacing longer previous tokens',
      'Regex Builder: Maps mods tokens all shortened — as Extr, ppress, educt, ower C, renzy, mum e, ne b replacing 10-17 char tokens',
    ],
  },
  {
    version: '1.0.45',
    date: '2026-04-24',
    changes: [
      'Regex Builder: tooltip token display fixed — no longer dark-on-dark, uses monospace with explicit light colour',
      'Regex Builder: all labels now use actual in-game mod text (e.g. Fecund — More Monster Life 90-100%, not High Life)',
      'Regex Builder: pack size mods now show their pack% bonus in the label (e.g. Shaper-Touched +20% pack)',
      'Regex Builder: Flask Effect label simplified to just show the secondary reward (+47%), penalty implicit in mod name',
      'Regex Builder: group labels show actual counts dynamically — removed hardcoded “5 Uber Mods” text',
      'Regex Builder: added Quantity Mods, Scarab Mods, and Maps Mods preset groups',
      'Regex Builder: Alt/Aug chisel toggle now directly adjusts the number boxes (±50) so the displayed value is always what\'s being searched',
      'Regex Builder: pack size default selection is the 4 Horsemen only (not all mods)',
    ],
  },
  {
    version: '1.0.44',
    date: '2026-04-24',
    changes: [
      'Regex Builder: all currency mod labels corrected — Stalwart (k at), Punishing (f ph), Diluted (sks), Ultimate (wb), of Defiance (xpir), Juggernaut (tunn), of Imbibing (eteor)',
      'Regex Builder: of Defiance (64% Currency, Debuffs expire faster) added as S-tier — was missing entirely from the preset',
      'Regex Builder: Juggernaut (Cannot be Stunned, 47% Currency) and of Imbibing (Meteor Flask, 45% Currency) added to currency pool',
      'Regex Builder: Alt/Aug crafting now uses ^Map of (confirmed working in PoE!) for suffix-only detection — prefix/suffix toggle removed, both patterns combined cover all cases with zero false positives',
      'Regex Builder: Alt/Aug explained: prefix-only map detected by " Map (Tier", suffix-only by "^Map of", full 2-mod map matches neither — stays dark correctly',
      'uberMapMods.ts: comprehensive update from full pasted mod pool — all mods, correct quant/rarity/pack values, verified tokens',
      'uberMapMods.ts: added Ultimate (Bloodstained Sawblades, 47% Currency) which was missing',
      'uberMapMods.ts: added regexToken field to every mod for direct stash regex use',
    ],
  },
  {
    version: '1.0.43',
    date: '2026-04-24',
    changes: [
      'Regex Builder: removed Originator Search preset as unnecessary',
      'Regex Builder: Quick Reference moved into mod badge tooltips — hover any mod for full text, token, and description',
      'Regex Builder: Alt/Aug crafting is now fully dynamic — adjustable currency min, pack size min, and giga-currency threshold',
      'Regex Builder: Avarice chisel toggle — when not yet applied, thresholds are lowered by 50 to match pre-chisel roll values',
      'Regex Builder: currency mod position toggle (Prefix vs Suffix) controls which open-slot pattern is used in gate 2',
      'Regex Builder: mod tooltips show full in-game mod text, regex token, and why the token was chosen to avoid false positives',
      'Regex Builder: currency mod labels marked [verify] where exact in-game mod name is uncertain — update once confirmed in game',
    ],
  },
  {
    version: '1.0.42',
    date: '2026-04-24',
    changes: [
      'New panel: Regex Builder — K-of-N combinatorial stash regex generator using Product of Sums logic',
      'Regex Builder: pick mods from preset groups (4 Horsemen packsize, 5 uber currency mods), set minimum K, generates correct AND-block regex automatically',
      'Regex Builder: supports multiple groups AND\'d together (e.g. 2 packsize AND 2 currency in one string)',
      'Regex Builder: custom token input for any mod not in the presets',
      'Regex Builder: live character count with 250-char PoE stash limit warning',
      'Regex Builder: crafting presets — Alt/Aug magic map crafting, 2+2 dual-gate, 3+2 god-tier, Originator search',
      'Strategy Browser: league filter now defaults to Mirage and reads from KNOWN_LEAGUES in league.ts',
      'Strategy Browser: hardcoded old league list removed — update league.ts to add future leagues',
    ],
  },
  {
    version: '1.0.41',
    date: '2026-04-24',
    changes: [
      'Atlas Tree: New Session no longer triggers atlas tree stat reading or leaves the pathofpathing stats panel open',
      'Atlas Tree: stats panel is now closed automatically when switching sessions',
      'League: simplified to Mirage only — removed Dawn of the Hunt, Settlers, Standard etc. from probe list',
      'League: easy to extend for future leagues — just update CURRENT_LEAGUE and KNOWN_LEAGUES at the top of league.ts',
      'Regex: fixed double-exclusion bug (“!”!…””) caused by corrupted regexExclusions containing full regex strings instead of bare terms',
      'Regex: sanitizeExclusionTerms() added — strips quotes, leading !, and rejects any term with special regex characters',
      'Regex: migration cleans corrupted regexExclusions and defaultExclusionPreset in all saved sessions on next load',
      'Regex: trade window regex now includes rarity (IIR) in the generated Copy Regex',
      'Atlas Calc: wizard now reactively watches settings values — no longer shows yes/no questions after Load Build Settings applies calc data asynchronously',
    ],
  },
  {
    version: '1.0.40',
    date: '2026-04-22',
    changes: [
      'Regex: fixed thresholdPat for currency floors 100–199 — e.g. 140% now correctly generates 1[4-9].|[2-9].. instead of the ambiguous \\d.. pattern',
      'Regex: removed “⚠ Open slot only for slam” note',
      'Trade: trade modal stays open after clicking Search so you can adjust filters and re-search',
      'Trade: Copy Regex button has fixed minimum width so it doesn’t resize when showing Copied',
      'Changelog: past versions are now collapsible — click any version header to expand its changes',
      'Tags: removed Titanic (not a meaningful build mechanic), restored Ambush (= Strongboxes, still in game)',
      'Types: removed sinistral/dextral from RegexSet type',
      'Trade: Shaper/Elder influenced and Conqueror-occupied maps are now always excluded from results',
      'Security: Atlas Tree and Atlas Calc URL checks now use proper hostname parsing, fixing all CodeQL high-severity alerts',
      'Suppress mods: split into three correct separate entries with accurate API needles',
    ],
  },
  {
    version: '1.0.39',
    date: '2026-04-21',
    changes: [
      'Strategy Browser: column layout overhauled — uniform gap spacing between all columns, consistent alignment across header and rows',
      'Strategy Browser: added Cost/map column showing per-map investment cost',
      'Strategy Browser: renamed Invest → Total Invest, Profit → Total Profit',
      'Strategy Browser: Author / Strategy header shortened to Author',
      'Strategy Browser: number formatting strips trailing .0 from k-values (107.0kc → 107kc, 3.6kc stays 3.6kc)',
      'Strategy Browser: Tags column widened to 140px with uniform 6px column gap for better 3-tag display',
      'Strategy Browser: tag abbreviations limited to genuinely compound names only (emp+orig, deli, astrolabe variants, boss, mirage) — all others kept as full names',
      'Strategy Browser: removed Harbinger and Metamorph from tag options (no longer in the game)',
      'Strategy Browser: Profit/map falls back to net_profit ÷ divine_price ÷ map_count when server stored null',
      'Strategy Browser: Discord export renamed Profit/map back to Div / Map to match server bot parser',
      'App: panel layout now persists across restarts — panels remember their position, size and which are open',
      'App: Reset layout to default option added to the + Add Panel menu',
    ],
  },
  {
    version: '1.0.38',
    date: '2026-04-20',
    changes: [
      'App: panel layout now persists across restarts — resize, reorder, and close panels and your layout is remembered',
      'App: “Reset layout to default” option added to the + Add Panel menu',
      'Strategy Browser: Profit/map now falls back to computing from net_profit ÷ divine_price ÷ map_count when the server stored it as null',
      'Strategy Browser: Tags column widened from 78px to 105px to comfortably show 3 tags',
      'Strategy Browser: Mod column has left padding so it no longer runs directly against the tags',
    ],
  },
  {
    version: '1.0.37',
    date: '2026-04-20',
    changes: [
      'Strategy Browser: 8-mod detection fixed — now uses the strategy\'s map_type field (6-mod/8-mod) instead of the content tag',
      'Strategy Browser: restored missing fallback for strategies without raw_export but with a stored run_regex',
      'Regex: paste preview field is now cleared automatically when switching sessions or loading a strategy',
      'Regex: reset button removed — the mod picker dropdown X button serves the same purpose',
      'Regex: Set Default button enlarged and renamed to “Set Default Preset” for clarity',
      'Regex: “Their exclusions” button renamed to “Show their exclusions ↑”',
    ],
  },
  {
    version: '1.0.33',
    date: '2026-04-19',
    changes: [
      'Trade: Instant Buyout fixed — status: available is the correct API value (confirmed via PoB URL inspection; online = In Person Online, available = Instant Buyout)',
      'Trade: Brick exclusion mod list now includes all monster-type mods (Inhabited by X, Increased Variety) and missing nightmare combined mods',
      'Regex: clearing the brick mod multiselect (X button) now clears ALL exclusions including custom terms',
      'Regex: paste preview shows full mod names instead of short terms — purple for nightmare, yellow for regular',
      'Strategy Browser: Load Build now populates a “Loaded from strategy” blue box in Regex with their averages and regex (with your exclusions applied)',
      'Strategy Browser: “Show their exclusions” button pastes the author’s original regex into the preview field so you can see what they were excluding',
      'Strategy Browser: Trade modal now pre-fills IIQ/IIR/Pack/Currency from the loaded strategy when no maps are parsed',
    ],
  },
  {
    version: '1.0.32',
    date: '2026-04-19',
    changes: [
      'Regex: new sessions start with no exclusions and no hardcoded fallback — generated regex is clean by default',
      'Regex: removed manual text entry field — replaced with regex paste preview that extracts exclusion terms and shows matched mods',
      'Regex: pasted regex terms matched to brick mod list with tooltips; Apply button adds them to exclusions',
      'Regex: brick exclusion ? tooltip reworded and fake mod examples removed',
      'Regex: nightmare mods coloured purple in both the brick exclusion picker and trade modal',
      'Strategy Browser: Load Build now saves the strategy run/slam regex as saved sets with your exclusions applied',
      'Trade: Instant Buyout fixed — status: online in the API query now correctly opens with Instant Buyout on the trade site',
      'Trade: Min Tier filter added (default 16) to exclude sub-T16 maps from results',
      'Trade: Corrupted override added — explicitly set Yes/No/Any independent of map type',
      'Trade: 0% delirium option added — requires the delirium enchant to be present at >=0%',
      'Trade: button label updated to show Instant Buyout is active',
    ],
  },
  {
    version: '1.0.31',
    date: '2026-04-19',
    changes: [
      // Regex — Brick Exclusion overhaul
      'Regex: Brick Exclusions now has a searchable mod picker (same full list as the Trade modal) — selecting a mod adds its short regex term to the chip list',
      'Regex: picking mods from the list and the chip list are fully bidirectional — deselecting a mod removes its term, removing a chip deselects the mod',
      'Regex: brick exclusion dropdown uses the same grouped data (Regular / Nightmare) as the Trade modal, computed once and shared',
      'Regex: Open Trade button is now always visible, not hidden when no maps are parsed',
      'Regex: new sessions start with empty brick exclusions — no pre-selected mods on a fresh session',
      'Regex: reset button clears all exclusions instead of restoring old hardcoded defaults',
      // Trade modal — brick exclusion sync
      'Trade: opening the trade modal auto-selects mods whose regexTerm is already in your brick exclusions',
      'Trade: → Sync to Regex Exclusions button pushes selected trade exclusions back as regex chip terms',
      'Trade: brick exclusion dropdown deduped by stat ID — no more Mantine duplicate options crash',
      // Map Analyzer tooltip
      'Map Analyzer: hover tooltip text colour fixed — explicit colour override prevents near-black text on dark background',
      // PoE Trade— mod list
      'Trade: brick mod definitions now include regexTerm for each of ~95 regular and nightmare map mods',
      'Trade: 8-mod map type now also excludes Originator maps (NOT originator implicit applied)',
    ],
  },
  {
    version: '1.0.30',
    date: '2026-04-19',
    changes: [
      // Map Analyzer
      'Map Analyzer: regular T16 maps now analysed with their own mod pool — separate from Originator/Uber mods',
      'Map Analyzer: grid auto-dispatches to correct analyser per map (isOriginator flag); Originator vs Regular T16 badge on tooltip + detail bar',
      'Map Analyzer: quality thresholds updated — Excellent = 4+ S/A mods (6 possible total, up from 3)',
      'Map Analyzer: multi-tab support — Tab 1/Tab 2 buttons appear when maps exceed the layout slot count',
      'Map Analyzer: Map Device layout auto-disabled when >20 maps are parsed',
      'Map Analyzer: chisel logic corrected — both Avarice and Proliferation bonuses are flat additive after the atlas multiplier, not multiplicative',
      // PoE Trade integration
      'Regex: "Open Trade" button opens a full search modal — map type (Regular/8-mod/Nightmare/Originator), Empowered Mirage toggle, Min IIQ/IIR/Pack, pseudo currency/scarabs/maps, delirium %, reward type multiselect',
      'Trade: delirium reward type uses OR logic (IF group) — map needs ANY of the selected types, not all',
      'Trade: delirium % filter correctly uses the enchant stat, not the explicit duplicate',
      'Trade: Originator implicit and Empowered enchant stat IDs fetched from PoE stats API at startup and cached; PoE2 groups skipped to avoid duplicates',
      'Trade: Nightmare type search uses NOT originator implicit + pseudo currency/scarabs/maps min to identify uber-mod maps',
      'Trade: modal auto-detects map type and empowered flag from your current parsed session',
      'Trade: pseudo stat IDs corrected to _currency_drops, _scarab_drops, _map_drops',
      'Regex: poe.re button removed — Open Trade replaces it',
    ],
  },
  {
    version: '1.0.27',
    date: '2026-04-18',
    changes: [
      'Regex: removed Sinistral/Dextral sections — 250-char limit makes them impractical',
      'Regex: poe.re button fixed (was 404), renamed to "Open poe.re", moved next to Save Run/Save Slam',
      'Map Analyzer: removed Sinistral/Dextral recommendation system and Paste tab',
      'Map Analyzer: grid now colors maps by quality tier (Excellent/Good/Decent/Standard based on S+A mod count)',
      'Map Analyzer: chisel recommendation (Avarice/Proliferation) shown as dot on each map cell and in detail bar',
      'Map Analyzer: summary badges now show quality tier counts and chisel counts',
    ],
  },
  {
    version: '1.0.26',
    date: '2026-04-18',
    changes: [
      'Fix: Excluded drops and Gem leveling lines restored to Discord export (were incorrectly removed in v1.0.25)',
      'Strategy Browser: Excluded drops now shown in expanded strategy card (parsed from raw export)',
      'Strategy Browser: Gem leveling now shown in expanded strategy card with buy/sell/net breakdown',
      'Import modal: Excluded drops and Gem leveling now shown when analysing a pasted export',
    ],
  },
  {
    version: '1.0.25',
    date: '2026-04-18',
    changes: [
      'Dashboard: Investment and Loot gain rows now show divine equivalent in grey (e.g. 158876c (491.88d))',
      'Atlas Calc: Atlas Bonus removed from the multiplier — it only affects Quantity, not all stats. Now shown as a separate note below the multiplier',
      'Dashboard: Quantity projection correctly adds the flat +25 IIQ from Atlas Bonus on top of the multiplier',
      'Strategy Browser: Invest and Profit columns now show divine sub-text in row and expanded card',
      'Strategy Browser: Div/map column renamed to Profit/map — the value is net profit in divines per map',
      'Discord export: removed Excluded drops and Gem leveling lines — app-internal info not relevant for strategy sharing',
      'Discord export: Build Type label renamed to Tags',
      'Discord export: Div / Map renamed to Profit/map',
      'Load Build: now correctly loads deli orb price, astrolabe count and price from raw export',
    ],
  },
  {
    version: '1.0.24',
    date: '2026-04-18',
    changes: [
      'Hotfix: bump store to v14 so mirageBonus → atlasBonus migration runs on existing sessions — Atlas Bonus now correctly preserved on update',
    ],
  },
  {
    version: '1.0.23',
    date: '2026-04-18',
    changes: [
      'Fix: Discord export now correctly accounts for baseline deduction and gem buy offset — Total Return and Net Profit now match the dashboard exactly',
      'Fix: Atlas Tree auto-apply no longer leaves the node stats overlay or pathofpathing stats panel open',
      'Renamed: "Mirage League" bonus is now labelled "Atlas Bonus" in Atlas Calc (field renamed atlasBonus)',
      'Strategy Browser: server URL field removed — server is now always the live endpoint',
    ],
  },
  {
    version: '1.0.22',
    date: '2026-04-17',
    changes: [
      'Strategy Browser: delirium orbs and astrolabe shown as headers in expanded strategy view',
      'Strategy Browser: Load Build Settings now also loads delirium orb type/qty and astrolabe type',
      'Strategy Browser: Import modal now shows deli orbs and astrolabe badges when present',
      'Share: astrolabe tag auto-added to build type tags when astrolabe is configured in Advanced Costs',
      'Investment: scarab cost field widened (was getting squished)',
      'Atlas Tree: auto-reads stats and applies to Atlas Calc after URL is imported or loaded from a build',
    ],
  },
  {
    version: '1.0.21',
    date: '2026-04-17',
    changes: [
      '8-mod auto-detect: now requires maps to be corrupted — Cartography Scarab of Risk no longer incorrectly flips sessions to 8-mod',
      'Discord export: delirium orbs now included (type, count, % delirious, cost/map)',
      'Discord export: slam regex omitted for 8-mod maps (corrupted maps cannot be exalted)',
      'Discord export: tag abbreviations in strategy list (emp+orig, a:enshr, etc.) — full name still shown on hover',
      'Dashboard: gem buy-back accounting — when gem name is configured and gems are excluded from loot CSV, buy cost is added back so gem activity is neutral to map profit',
      'Server (bot): incomplete exports now rejected — DM sent listing missing fields; message deleted from channel',
      'Server (bot): astrolabe tags auto-assigned from astrolabe type name in export',
      'Server (bot): delirium orbs parsed from export',
    ],
  },
  {
    version: '1.0.20',
    date: '2026-04-15',
    changes: [
      'Build fix: escaped quotes in Gem Leveling description',
      'Map subtype detection: sessions loaded from storage now re-detect Empowered Mirage / Originator from rawText — fixes wrong \'regular\' tag on old sessions',
      'Share: subtype tag detection uses rawText fallback for all maps, not just stored flags',
      'Discord export: slam regex suppressed for 8-mod maps (corrupted, can\'t exalt)',
      'Discord export: astrolabe line added when astrolabe is configured',
      'Share modal: teal alert when an astrolabe is set — prompts user to verify count before sharing',
      'Strategy Browser: astrolabe tags added (generic + per-type)',
      'Regex panel: 8-mod / Nightmare maps suppress slam with a note; poe.re button copies run regex and opens poe.re/maps',
      'Dashboard: baseline import tip explaining the investment double-dip risk',
    ],
  },
  {
    version: '1.0.19',
    date: '2026-04-15',
    changes: [
      'Gem Leveling: now tracks buy price + sell price separately — shows net gem P&L',
      'Gem Leveling: add gem name to auto-exclude matching items when a loot CSV is imported',
      'Gem Leveling: buy/sell/net breakdown shown in the Gem Leveling section of Advanced Costs',
      'Gem Leveling: export shows buy total, sell total, and net P&L as a separate note',
      'Gem badge now shows net P&L in green/red (positive/negative) instead of a flat total',
    ],
  },
  {
    version: '1.0.18',
    date: '2026-04-15',
    changes: [
      'Notes: now per-session — saved and loaded with each session, cleared on new session',
      'Gem leveling: removed from investment cost — it is side income, not a map expense',
      'Gem leveling: now shown as a separate violet “Side income” badge below investment costs',
      'Eater/Exarch tags: removed from scarab auto-detection (they are atlas tree nodes, not scarabs)',
      'Eater/Exarch: still correctly auto-detected from atlas tree node stats when you Read Stats',
    ],
  },
  {
    version: '1.0.17',
    date: '2026-04-15',
    changes: [
      'Regex: Brick Exclusions editor in Regex panel — add/remove terms, live preview, reset to defaults',
      'Regex: generated run/slam regex now uses your saved exclusion list',
    ],
  },
  {
    version: '1.0.16',
    date: '2026-04-14',
    changes: [
      'Notes tab restored: global scratchpad that persists across sessions (never cleared)',
      'Investment: Gem Leveling section in Advanced Costs — tracked separately from profit',
      'Export: excluded drops listed in the Discord export with names and values',
      'Export: gem leveling shown as optional income note when filled',
      'Share modal: warning when investment costs are 0',
      'Strategy Browser: map count column no longer shows \"m\" suffix',
      'Strategy Browser: Eater of Worlds + Searing Exarch tags added',
      'Atlas Tree: Eater/Exarch auto-detected from tree node group titles',
      'Atlas Calc: wizard now skips to done when a real tree URL is loaded (fixes Load Build Settings annoyance)',
      'Regex: exclusion list is now configurable per session (\"regexExclusions\" in settings)',
    ],
  },
  {
    version: '1.0.15',
    date: '2026-04-14',
    changes: [
      'Dashboard: multiplier now includes Mirage League +25% flat IIQ — was showing 0.25× less than Atlas Calc',
      'Strategy Browser: column headers now perfectly aligned with data rows',
      'Strategy Browser: Tags column wider (96px, 3 chips visible), better use of available space',
      'Strategy Browser: map-type tags (regular, originator, empowered etc.) now show tooltip on hover',
      'Sessions: Import on left, Share on right',
      'Atlas Tree: Apply to Calc button moved to toolbar (visible after Read Stats)',
      'App: version number shown in title bar next to WRAECLASTLEDGER',
    ],
  },
  {
    version: '1.0.14',
    date: '2026-04-14',
    changes: [
      'Strategy Browser: session notes field in Share modal — shown in the browser and import modal',
      'Atlas Tree: import URL button (📎) — paste any pathofpathing.com URL to load that tree',
      'Atlas Tree: “Apply to Calc” button in stats overlay auto-fills small nodes, Mounting Modifiers, fragments',
      'Sessions: panel now scrolls the entire card when history is long',
    ],
  },
  {
    version: '1.0.13',
    date: '2026-04-14',
    changes: [
      'Notes tab: per-session freeform notes saved with each session (Map Log tabset)',
      'Investment: clearer descriptions on Rolling Costs and Split Session sections',
      'Sessions: notes saved/loaded alongside maps and loot when using Save/Update/Load',
    ],
  },
  {
    version: '1.0.12',
    date: '2026-04-14',
    changes: [
      'Sessions: history list now properly scrolls when there are many sessions',
      'Sessions: Share and Import buttons added directly to the Sessions panel',
      'Investment: reset button (×) clears all costs while keeping divine price',
      'Atlas Calc: improved tooltip hints on Mounting Modifiers and Multiplying Modifiers',
    ],
  },
  {
    version: '1.0.11',
    date: '2026-04-14',
    changes: [
      'Sessions: Save as New no longer requires maps to be parsed',
      'Strategy Browser: Author column now shows strategy name (if set); tag column shows multi-tag chips with overflow tooltip',
      'Strategy Browser: Invest column now uses consistent fc() formatting matching Profit (e.g. 6.7kc)',
      'Strategy Browser: Date column hidden by default — click the ··· header to toggle it back on',
      'Strategy Browser: map subtype tags added (regular, originator, empowered, empowered-originator, nightmare, mixed)',
      'Strategy Browser: Share modal auto-detects map subtype from parsed maps + merges atlas tree tags',
      'Atlas Tree: reading stats now infers strategy tags from allocated node group titles (Delirium, Beyond etc.)',
    ],
  },
  {
    version: '1.0.10',
    date: '2026-04-14',
    changes: [
      'Map parser: Strategy Browser now appears as a default tab next to Map Log — no more manual adding',
      'Map parser: fixed mod count for corrupted and Nightmare maps — 8-mod detection now correct',
      'Map parser: detects Originator maps, Empowered Mirage maps, Nightmare maps, and corrupted maps',
      'Map parser: strips PoE color tags (<tag>{content}) before parsing — corrupted map mods now parse correctly',
      'Map parser: all four detection fields stored per map for future statistics use',
    ],
  },
  {
    version: '1.0.9',
    date: '2026-04-14',
    changes: [
      'Strategy Browser: multi-select type tag filter — filter by Delirium + Beyond + Legion simultaneously',
      'Strategy Browser: league filter — show only Mirage / Dawn of the Hunt / etc. strategies',
      'Discord export: league name included automatically (auto-detected from poe.ninja on startup)',
      'Atlas Calc: map type auto-detected from parsed maps — switches 6-mod ↔ 8-mod when ≥4 maps confirm it',
    ],
  },
  {
    version: '1.0.8',
    date: '2026-04-14',
    changes: [
      'Atlas Tree: Read Stats now captures ALL node groups (Beyond, Delirium, Shrines etc.) — fixed lazy-render issue',
      'Atlas Calc: Mirage League +25% flat IIQ bonus toggle — on by default, turns off next league',
      'Strategy Browser: time period filter — All time / Last 24h / 3 days / 7 days',
      'Strategy Browser: Boss Rush and Mirage Rush added as strategy type tags',
      'Strategy Browser: multiplier export now includes Mirage League bonus when active',
    ],
  },
  {
    version: '1.0.7',
    date: '2026-04-14',
    changes: [
      'Strategy Browser: Discord export and import moved here — the natural home for community sharing',
      'Strategy Browser: "Share My Session" button — export preview with tag selector, one-click copy',
      'Strategy Browser: "Import" button — analyse any export at your current divine price',
      'Map Log: simplified back to pure map tracking — no export clutter',
      'Sessions panel: simplified — session management only, no import modal',
      'poe.ninja: removed dead getindexstate endpoint call — no more 404 console noise',
      'DevTools no longer open automatically in production builds',
    ],
  },
  {
    version: '1.0.6',
    date: '2026-04-14',
    changes: [
      // Strategy Browser
      'Strategy Browser: community strategy feed — browse builds posted by your group',
      'Strategy Browser: filter by build type (Delirium, Legion, Breach, etc.), min div/map, and sort',
      'Strategy Browser: "Load Build Settings" imports scarabs, chisel, and atlas tree in one click',
      'Strategy Browser: "View in Discord" button links directly to the source message for voting',
      'Strategy Browser: strategy scores via 👍/👎 Discord reactions — sort by Top Rated',
      'Strategy Browser: regex displayed with one-click copy buttons',

      // Discord export
      'Discord export: optional Build Type tag selector — overrides auto-detection from scarabs',
      'Discord export: tag appears in Strategy Browser and is filterable',

      // Atlas Tree
      'Atlas Tree: reloads automatically when "Load Build Settings" is used',
      'Atlas Tree: correctly persists per-session — load/new session always shows the right tree',

      // App polish
      'Map Analyzer: stash grid and legend centered',
      'Dashboard: stat box labels embedded in box, projected values larger',
      'Dashboard: loot list uses smart load-more (25 at a time)',
      'Dashboard: clearing loot now asks for confirmation',
      'Investment: cost badges centered, divine price box properly aligned',
      'Investment: Advanced Costs sections start collapsed',

      // Data fixes
      'Scarab list: fully corrected against wiki — fixed typos, added 11 missing entries',
      'Atlas Calc: "Uncharted Realms" corrected to "Multiplying Modifiers"',
      'Content Security Policy: HTTP strategy servers now work alongside HTTPS',
    ],
  },
  {
    version: '1.0.4',
    date: '2026-04-14',
    changes: [
      'Atlas Tree: tree persists per-session and resets on new session',
      'Dashboard: stat boxes redesigned — labels inside, larger projected values',
      'Dashboard: loot smart load-more, clear confirmation, loot fills remaining space',
      'Investment: cost badges centered, divine price box aligned',
      'Investment: Advanced Costs sections start collapsed',
      'Map Analyzer: layout dropdown (Map Tab / Regular / Quad / Map Device)',
      'Map Analyzer: stash grid centered',
      'Atlas Calc: wizard resets correctly on session change, pill edit goes back to single question',
      'Scarab list: corrected against wiki, 11 missing entries added',
      'Atlas Calc: "Uncharted Realms" → "Multiplying Modifiers"',
      'Auto-updater: public repo, background checks working',
    ],
  },
  {
    version: '1.0.1',
    date: '2026-04-13',
    changes: [
      'Merged Statistics + Loot into a single Dashboard panel with collapsible sections',
      'Advanced Costs modal: scrollable, all sections always accessible',
      'Investment: divine price and rolling cost in a boxed layout',
      'Investment: collapsible cost sections, active costs shown as clickable badges',
      'Atlas Calc: step-by-step wizard for first-time setup; compact pill view after',
      'Atlas Tree: URL saves on every navigation, included in Discord export',
      'Discord export: readable markdown format, imports from both raw and rendered',
      'Scarab clear (×) button inside the autocomplete field — no layout shift',
      'Split session: price-per-split field, auto-counts from parsed maps',
      'Chisel: Cartographer added, bonus correctly shows +10% Quantity',
      'App title renamed to WraeclastLedger throughout',
      'Installer now prompts for installation directory',
      'Check for Updates button in toolbar',
    ],
  },
  {
    version: '1.0.0',
    date: '2026-04-11',
    changes: [
      'Initial release',
      'Map Log with live clipboard capture (Ctrl+C in-game)',
      'Atlas Calc: multiplier from fragments, nodes, and mounting bonuses',
      'Investment panel: scarabs, chisel, delirium orbs, astrolabes, split session',
      'Statistics: base → projected with chisel and quality awareness',
      'Loot tracker: baseline / return CSV diff view with category breakdown',
      'Regex generator with trimmed mean (run / slam filters)',
      'Map Analyzer: stash grid + paste analyzer for T16.5 Originator maps',
      'Atlas Tree viewer via pathofpathing.com',
      'Session save, load, rename, delete',
      'Discord export and import (markdown format)',
      'Auto-update via GitHub Releases',
    ],
  },
];
