/**
 * CHANGELOG — WraeclastLedger
 * Add new entries at the TOP. The "What's New" banner shows entries ≥ current version.
 */
export interface ChangelogEntry {
  version: string;
  date: string;
  changes: string[];
}

export const CHANGELOG: ChangelogEntry[] = [
  {
    version: '1.0.70',
    date: 'Unreleased',
    changes: [
      'Atlas Tree now opens older live and historical allocations against the active 3.29 tree while preserving their exact authored URLs. A provenance badge explains the shown version and offers Load original whenever the view was retargeted.',
      'The 3.29 game-data bundle now uses GGG\'s official Abyss Scarab of the Consort name and the verified Path of Pathing 3.29.0-atlas version.',
      'Strategy Browser now includes a Retrospectives view. Close out each league with an explicit UTC cutoff, then reopen or compare qualifying saved sessions in the Personal board. Published snapshots appear separately as immutable Top Rated and Top Profit boards, with captured cutoff/provenance, an always-visible Author-reported warning on profit rankings, compatibility badges, and frozen builds that can be viewed or loaded but never updated.',
      'Map Search (poe.re) has been fully retired now that the built-in Regex and PoE Trade tools cover its useful workflows. Fresh layouts no longer include it, and saved layouts remove every old Map Search tab automatically without disturbing neighboring panels.',
      'Share My Session now shows a live Discord card size meter and caps notes to what actually fits the 2,000-character card, so shares can never be silently truncated and you can see up front whether your card keeps its custom emotes. Strategy names are capped at 80 characters with a hint that they are public labels, not your private session names.',
      'Sharing is disabled with a clear explanation when the session belongs to an ended league (its results live on in Retrospectives) or when no league is confirmed yet — the Discord bot would reject those exports anyway.',
      'Atlas Tree: Recenter (reload) now reloads the tree exactly as it currently is — previously it silently rewound every node allocated since the panel loaded and could overwrite the newer captured tree with the stale one. Viewing node stats no longer leaves Path of Pathing’s own stats window stuck open behind ours, and the stats overlay gained its own Apply to Calc button so view-then-apply is one click.',
      'Sessions: selecting history entries no longer shifts the list — the Export/Delete bar now reserves its space and simply appears in place, so nothing jumps under your cursor.',
      'Atlas Calc: the multiplier hero card now sits on the same neutral surface as its sibling sections instead of a glowing blue box, and all breakdown numbers round to one decimal when an observed average produces fractional mod counts (the math itself is unchanged).',
      'The Discord export got leaner so more cards keep their custom emotes: the duplicate title line is gone, shared regexes no longer carry your personal brick exclusions (receivers regenerate with their own — the neutral form is more useful to everyone else), and scarab bullets render flat instead of oddly nested. The size meter now mirrors the slimmer bot card, so the notes budget grew accordingly.',
    ],
  },
  {
    version: '1.0.69',
    date: '2026-07-17',
    changes: [
      'Development and installed builds now use separate local profiles, and each profile permits only one running app instance. Side-by-side release testing can no longer make two Electron processes write the same pre-migration localStorage database. A second launch focuses the existing window instead.',
      'Game data is classified for Path of Exile 3.29: the new Trarthan Scarabs are available, renamed Abyss Scarabs and the Deceptive Astrolabe preserve their historical aliases, and Heist/Metamorph Scarabs plus unavailable Delirium Orbs are removed from new-input pickers without erasing old sessions. Reworked products keep clean names on input surfaces, while compatibility checks retain their lifecycle context. Map-splitting costs are likewise hidden for new 3.29 sessions while historical split sessions remain editable.',
      'Atlas Calc now leads with its multiplier and keeps the detailed breakdown and configuration in compact summary bars. Map Type moved into Configuration beside a 2-by-2 settings grid, while the existing observed-mod lock, Atlas Bonus behavior, wizard answers, sliders, and multiplier math remain unchanged.',
      'Investment now places its scarab Presets action in the centered Scarabs divider, with a compact tooltip lock when Preservation is active. This removes the otherwise empty control row without moving scarab inputs or cost badges.',
      'Regex Builder now keeps one mod group open at a time, summarizes configured groups as compact pills, and aligns the generated regex beside the active group with its exact character budget and requirements. Matching section bars replace the loose collapsibles, duplicate inner titles and the unnecessary short-list search are gone, existing presets cannot be added twice, and the layout stacks based on the dock panel itself while K-of-N and Alt/Aug output stays byte-identical.',
      'PoE Trade reward selection keeps its original searchable multi-select layout while pinning the clear and dropdown controls to the top-right as selected pills add rows. The green league name is now clickable for a search-only league choice without rewriting a loaded historical session.',
      'Strategy Browser now shows the exact observed modifier average shared from fully advanced-copied map sets in its Mod column, with the sample size and unchanged 6/8-mod filter bucket explained on hover. Older shares continue to show their 6-mod/8-mod type.',
      'Map Analyzer has been retired: it no longer had a useful decision to support. Fresh layouts and Add Panel no longer offer it, and existing saved layouts remove the old tab automatically without disturbing neighboring panels.',
      'The hidden Atlas Tree stats reader now rejects an untrusted final redirect before reading the page and serializes concurrent requests so only one isolated reader window can exist at a time.',
    ],
  },
  {
    version: '1.0.68',
    date: '2026-07-16',
    changes: [
      'League rollover caches are now context-safe: an event ending while the app remains open triggers a fresh league probe, a divine price from the previous league is never treated as fresh for the new one, and item icons rebuild after automatic or manual league changes.',
      'The title bar now shows the active game-data revision and its source on hover, and turns the badge yellow when the remote or cached manifest is unavailable, invalid, or incompatible. Future manifest revisions declare a schema and PoE context before the app will adopt them.',
      'Newly shared strategies now record the exact game-data revision and patch active when each result was authored. Strategy cards show this provenance, while historical shares remain valid without it.',
      'Atlas Tree no longer initializes its embedded renderer while its dock tab is hidden or zero-sized. Hidden-tab activation, session/strategy loads, URL imports, and manual recenter now remount the saved tree only after the panel has settled.',
      'League data now drives the live Investment pickers: reworked items remain selectable and carry a visible warning, while removed items disappear only from new-input choices without erasing historical sessions.',
      'Sharing is blocked when the captured Atlas allocation exceeds the tree maximum, with a direct explanation of how to correct it; the invalid export preview is withheld too.',
      'Getting Started, the empty Map Log, and the Pace tooltip now explain the intended copy-before-each-map workflow and that pasting an old batch cannot reconstruct playtime.',
      'Map Log duplicate hints now catch exact repeated parses anywhere in the current session, including A/B/A/B paste patterns; maps differing in even one parsed stat remain unflagged.',
      'Dropping exactly two WealthyExile CSVs onto Dashboard now previews both filenames and totals and asks which is the baseline; the other becomes the return, and Cancel imports neither.',
      'The app identity, version, data revision, and update control are centered against the full window again, independent of the Add Panel control width.',
      'Advanced Ctrl+Alt+C map copies now record an exact explicit-affix count from modifier headers, shown in Map Log’s Mods column. Atlas Calc prefers that fact for 6/8-mod auto-detection; normal Ctrl+C remains supported through the existing fallback.',
      'Turning Capture on no longer logs stale map text that was already sitting in the clipboard; only a subsequent copy is captured, while Paste remains the explicit way to parse existing clipboard content.',
      'Mixed alch-and-go sessions now use their exact observed modifier average for Mounting Modifiers once at least four maps have complete Ctrl+Alt+C coverage. Atlas Calc locks the 6-mod/8-mod fallbacks while observed evidence exists and carries the same multiplier into Dashboard projections, comparisons, and shared exports.',
      'Capture always starts paused after restarting the app, even if it was active when the previous run closed.',
      'Atlas Calc stays compact in narrow panels: map-type labels no longer wrap into boxes, observed evidence locks the fallback pills, and the duplicated header multiplier was removed while the detailed total remains below.',
      'Dock panels now adapt to their own width rather than the app window: Atlas Calc right-aligns its map-type pills and hides locked fallbacks only when necessary, Sessions shortens action labels without adding rows, and Investment safely wraps its header. Dashboard preserves its denser two-column comparisons in smaller desktop windows.',
      'Strategy Browser now preserves a readable minimum table width and offers horizontal scrolling below it instead of silently cutting off filters and result columns; compact Investment keeps its league selector and cost-per-map summary on one row.',
      'League rollover safety: an unnamed working session carried from the previous league is never silently restamped or repriced. The app pauses automatic mutation, shows a clear warning, rejects Standard provenance, and waits when no supported league is confirmed.',
      'Loading or importing Strategy Browser build settings now protects every meaningful unnamed session, including loot, notes and configured setup without maps: save it, explicitly discard it, or cancel before replacement.',
      'The working-session guard now ignores untouched Atlas Tree metadata and no longer reopens the Sessions picker after a decision. Strategy Browser tree settings populate Atlas Calc through an isolated one-shot reader even while Regex is selected; the visible tree still mounts only at a safe panel size.',
      'Missing item artwork now uses an honest category symbol where the item type is known, while unknowns stay blank. False matches involving Heist Scarabs, Blueprint wings and fragment-like card names were removed; cards are identified from their real display names and use the shared inventory icon, plain map tiers use only clean signed art and otherwise show the neutral map symbol instead of a Blight/conqueror/event overlay, unique 6L names resolve by their base item, and non-square equipment art keeps its proper proportions.',
      'Loot search covers the complete imported list and now preserves the number of rows you previously revealed when searching or clearing the filter.',
      'Older saved panel layouts automatically remove the obsolete duplicate Regex Builder tab while preserving a lone Builder as the merged Regex panel.',
      'Atlas Calc choices and Strategy Browser sort headers now use native keyboard-operable controls without changing their mouse layout; Tab reveals focus and Enter or Space activates the focused control.',
    ],
  },
  {
    version: '1.0.67',
    date: '2026-07-14',
    changes: [
      'Advanced Costs now opens another category on the first click after entering a Delirium Orb or Astrolabe price; revealing the calculated summary no longer shifts the clicked category away.',
      'Atlas Calc now previews the real prospective Mounting Modifiers bonus instead of showing +0%, and correctly describes Mounting, Multiplying, and the small Atlas nodes as increased effect of Explicit Modifiers rather than direct IIQ.',
      'Share My Session now calls its classifications “Strategy type tags” and describes the strategy rather than the build.',
    ],
  },
  {
    version: '1.0.66',
    date: '2026-07-14',
    changes: [
      'Update your published strategies: expand one of YOUR cards in the Strategy Browser and hit "Update strategy" — your setup (scarabs, chisel, atlas tree, deli orbs, astrolabe) is cloned into a fresh session for a new measurement run. Sharing that session replaces the published result in place: same Discord card, votes and post date kept, revision counter bumped.',
      'The Share dialog shows when a session is an update run ("Updating <name>") with a one-click "Share as new strategy instead" opt-out. The update target survives app restarts and save/load with its session; brand-new sessions never carry one, and importing someone else\'s update export never turns you into its updater.',
      'Updated strategies show a vN badge in the Strategy Browser with the last-updated date in its tooltip (v1 originals stay unbadged).',
      'Fixed: loading a strategy (Load setup or Update strategy) a second time in a row now correctly re-fills the Atlas Calc from the tree instead of dropping you back into the setup wizard.',
      'Historical sessions stay compact in Investment: their frozen league is now part of the Divine Price label (hover it for the full explanation), so the status never steals a row or gets clipped in a short panel.',
      'Atlas Bonus (+25% IIQ for completing all 100 Atlas Objectives) is now tracked per league. The setup wizard asks about it as a 4th step, your answer is remembered for that league across new sessions, and it resets when a new league/event starts — so you set it once per league and never carry a stale +25% into the next one. New sessions only apply it once the active league is actually known (never guessed from an offline fallback). When it is off and unset for the current league, a subtle, dismissible reminder appears so the bonus is never silently missed.',
      'Strategy Browser now has a div/h column (author-reported divines per hour), sitting just left of Profit/map (which stays the rightmost column) — it shows "—" for strategies that did not share a session time, and clicking the header sorts by it (unshared-time strategies list after the ranked ones, never penalised).',
      'Strategy Browser columns now use one shared grid, so headers stay aligned with every strategy row. The calendar column and toggle are gone; expanded cards now show the full strategy name, publication date, and (for revisions) last-updated date. Tags safely collapse into a "+N" badge before a scrollbar or narrow panel can cut one off.',
      'When you\'re updating one of your published strategies, the Share dialog now shows a neutral before/after comparison — maps, avg map stats, div/map, cost/map, invest and profit — against the currently published version, with directional arrows so you can see what changed without labeling larger or smaller numbers as inherently better or worse.',
    ],
  },
  {
    version: '1.0.65',
    date: '2026-07-11',
    changes: [
      'Saved sessions are now protected from silent repricing: opening a saved session no longer auto-refreshes its divine price or re-stamps its league — a session\'s numbers stay exactly as you saved them, whether it\'s from this league or an old one. The refresh button on a saved session now asks first ("Reprice using current economy") and never touches the league.',
      'Sessions from a previous league show a "Historical session" notice on the Dashboard and Investment panels, and their atlas point counts can no longer be overwritten by opening their tree under a newer patch.',
      'A failed divine-price fetch can no longer wipe a valid price — the old value is always kept until a fetch actually succeeds.',
    ],
  },
  {
    version: '1.0.64',
    date: '2026-07-11',
    changes: [
      'League detection knows when events end: once the Ancestors event closes (~July 16), the app automatically moves to Mirage for prices, trade links, and the Strategy Browser default — no more being stuck on a dead league until the next app update. The ended event stays selectable manually if you need it.',
      'Game-data hotfix channel is live: the app now checks the strategy server for a newer game-data revision at startup (scarab/orb/chisel lists, mechanic flags) and adopts it without needing an app update. Server unreachable or nothing newer = exactly the behavior you had before, silently.',
      'Click the version number in the title bar to reopen this What\'s New panel any time — it no longer disappears forever after the first dismiss.',
      'Strategy Browser refreshes itself every 5 minutes (first page only, and never while you\'ve paged deeper into the list), so new shares and votes show up without hitting Refresh.',
      'Regex — From Session reordered: the generated (or loaded-strategy) regex with its copy / save / Open Trade actions now sits at the TOP of the tab, so filling out Brick Exclusions can no longer push your output out of view. The exclusion mod pickers\' clear × and dropdown arrow stay pinned to the top-right as the field grows.',
      'Regex panel: the × on the "Default set" badge joins the standard neutral style (red on hover) instead of teal.',
      'Advanced Costs: the Rolling Costs rows are aligned again — the per-orb "each" caption under Exalted now sits in the price column instead of shoving the icons around.',
    ],
  },
  {
    version: '1.0.63',
    date: '2026-07-10',
    changes: [
      'New: compare 2-3 saved sessions side by side — pick them in the Sessions panel and hit Compare for an aligned stat table (profit, div/map, invest, multiplier, maps and more) with the best value per row highlighted.',
      'New: a Getting Started card welcomes fresh installs on the Dashboard — the essential first steps (capture a map, import loot CSVs, set your divine price) with pointers to the right panels. Dismissable, and it stays gone.',
      'Share dialog: set your Discord name once and your own strategies get highlighted in the Strategy Browser so you can spot them in the list.',
      'Sharing knows more, only if you want: the Share dialog gains a party-size field (2-6, shown when Group is selected) and a session-time field prefilled from your Pace estimate (breaks excluded; accepts 90, 90min, 1.5h and friends). Atlas points are captured automatically from the Atlas Tree panel. All three are optional — leave them empty and the export simply makes no claim.',
      'Strategy cards show the author\'s session context when shared: time with a derived div/h (optional author-reported context; selectable as a sort while div/map stays the default) and atlas points in the expanded card; the group badge names the party size when known.',
      'Strategy Browser: column headers are click-to-sort — Cost/map, Total Invest, Total Profit, Score, and Profit/map set the sort on click and flip direction on a second click (arrow shows the active sort). The sort dropdown gained Cheapest /map and Best d/hour; d/hour comes from author-reported session time and never outranks strategies without it (they just list after the ranked ones).',
      'Import Strategy preview catches up with what the parser already reads: the strategy name headlines the preview, and Group (N players), session time, and Atlas points badges appear when the export carries them. Scarabs show as icon badges with their costs instead of a plain text list.',
      'Discord sharing, part 3 (needs the server deploy): the channel bot now re-posts your export as a formatted card crediting you, and removes your raw paste once it is saved — the channel stays clean and the card itself can be copied straight back into Import Strategy. Reactions (votes) live on the card.',
      'Map Log: rows identical to the previous map get a small "dup?" marker \u2014 accidental double-pastes are now visible and one-click deletable, while genuinely identical maps just carry a harmless hint (hover it for details).',
      'Getting Started card gained a "good to know" footer: loaded sessions auto-save (use Save as New to fork before experimenting), and a reminder that the Atlas Bonus toggle exists once your 100 objectives are done.',
      'The Pace (estimate) tooltip now spells out what it measures: first captured map to your last activity, break-like gaps excluded, needs 5+ maps, local-only.',
      'Strategy Browser: the Mod, Cost/map, and Score column headers explain themselves on hover (Cost/map is all-in: total investment divided by map count).',
      'Clearing session notes now asks for confirmation \u2014 with auto-save, a misclick on the trash icon used to wipe your notes permanently within a second.',
      'Loot Tracker joins the thousands-separator club: item values, the totals badge, Net Gain, diff deltas, the breakdown categories, and the baseline badge all read as 1,234.5c now. Same for Session costs in the Investment panel and the Session costs (total) line in Advanced Costs.',
      'Drag & drop CSV import: drop a WealthyExile CSV anywhere on the Dashboard and it asks whether it is a baseline or session loot — no file dialog needed. The classic Baseline/Return buttons are unchanged.',
      'Strategy cards: the expanded stat tiles are centered like the Dashboard tiles, and Run/Slam regex lines start at the same offset everywhere (fixed-width role badge).',
      'Strategy cards also show the author\'s atlas multiplier as its own tile (hover it: the stat tiles are base, unprojected averages — loading the build projects them for YOUR maps in the Dashboard).',
      'Regex: hover the Run/Slam badges for an explanation of how each regex is derived (Run = your session floors; Slam = 75% currency/pack near-misses worth upgrading).',
      'Regex: named exclusion presets — save rotating brick-exclusion setups by name and load them from the new preset row (same pattern as scarab presets). The Default preset badge now has an × to clear it, replacing the old empty-list-then-Set-Default trick.',
      'Regex panel redesign, Brick Exclusions edition: save/load/set-default consolidated into ONE compact Presets menu (naming happens in a small dialog — the giant always-visible name field is gone); the mod picker is now two side-by-side searchable lists, Regular and Nightmare, so nightmare mods no longer live at the bottom of one long dropdown; the paste-a-regex importer got its own labeled box; the ? tooltip was rewritten; and the "Default set" badge moved into the panel tab bar (bigger, with a proper ×).',
      'Investment: the scarab preset controls got the same treatment — one Presets menu instead of the permanent name field + separate Load button, with scarab lists shown on hover.',
      'Fresh coat of paint, part 5: the remaining colored secondary buttons went neutral — Set Default Preset and Copy Regex (Regex panel), Save as Set and the Builder group delete (now the standard bordered red-hover trash), Apply to Calc and the Atlas Tree toolbar icons. Primary actions (Open Trade, Search on PoE Trade, Load Build Settings, copy confirmations) keep their color.',
      'Item icons, big fix batch: maps no longer wear the wrong art (a T16 could show a Vaal Temple, blighted, or old-generation icon depending on fetch luck — icons now resolve per tier with clean art preferred, current league first); gems like "Precision - 21/20 corrupted" and variant-listed uniques like "Focal Point, Forbidden Flame" now resolve to their real icons instead of blanks; uncached "...Orb" names no longer masquerade as Chaos Orbs.',
      'Big chaos numbers are readable: +107,047c instead of +107047c across the Dashboard profit tiles and the strategy card details (cost/map, total invest, base + session, scarabs, all-in). Divine values keep their compact form.',
      'Dashboard layout: the maps/multiplier pills moved into the Map Multipliers section header where they belong, and Investment + Loot gain became a quieter second tile row under the two big profit tiles. Advanced Costs, the divine refresh, and the version badge dropped their odd colors for the app-wide neutral style.',
      'Fixed typing and toggle lag: every panel used to re-render on every keystroke (Notes, scarab names, filters) because they all listened to the whole session state. Panels now subscribe only to the data they actually show — typing in one panel no longer redraws the Map Log table, the loot list, or the Map Analyzer grid.',
      'Review fixes: the Atlas Calc multiplier pill and the Notes session badge were genuinely a size off from their Dashboard/Sessions counterparts — all pills and dot-badges now share one size. Regex Run/Slam lines are vertically centered against their copy buttons and sit tight together in every panel.',
      'Panel headers declutter: the redundant in-panel titles (Atlas Calc, Dashboard, Strategy Browser, Notes, Map Log, Map Analyzer) are gone — the tab already names the panel — and the freed row now holds something useful: Map Type moved into the Atlas Calc header, the strategy count reads "N strategies", Map Log leads with the Capture toggle and map count, Map Analyzer\'s layout picker moved up.',
      'Atlas Calc: the configuration pills collapse into a "Click to edit" section once set up, and Atlas Bonus is now a fourth pill there (click toggles it directly) instead of a bottom-row switch; when active it shows as a normal breakdown row. The Scarab of Risk row is tinted light-blue to mark it as coming from your scarab choice, not this panel\'s config.',
      'Regex — From Session: Save Run/Slam As and Show-their-exclusions are now standard neutral buttons, and Open Trade moved into the regex box itself (right-aligned next to the save buttons) so it stops floating loose at the panel bottom.',
      'Investment: the reset-all-costs button moved inside the costs box, next to Advanced Costs — it resets exactly what that box configures.',
      'Advanced Costs: the Rolling Costs rows (Chaos/Exalted/Scour/Alch) show their orb icons, the gem-name field shows the gem\'s icon once it resolves, and the Split section shows the Fractured Fossil icon.',
      'Strategy Browser: the group filter button now reads "Show group" while group strategies are hidden.',
      'The Map Search (poe.re) panel is retired from "+ Add Panel" — the built-in trade search and regex tools superseded it. Layouts that already contain it keep working.',
      'Fresh coat of paint, part 4 — consistency pass: every icon action across the app (delete/clear/reset/undo/copy/save/refresh) is now a real bordered button with a tooltip, sized to match the Sessions panel; destructive ones are neutral until you hover them (muted red), and row-level deletes (Map Log) only appear when you hover the row — the same interaction language the Sessions panel already used.',
      'New safety confirmations: clearing the Map Log and deleting a saved regex set now ask first — both were one-click permanent destruction. Per-map removal and Builder group removal stay instant.',
      'One pill style everywhere: the atlas multiplier badge (Atlas Calc header now matches the Dashboard), the map-count badge, the Investment c/map badge and the Strategy Browser count all use the same outlined treatment instead of four different fills.',
      'Atlas Calc: calmer colors — config pills and the map-type selector share one blue active accent, the breakdown values are plain text (Mounting lost its orange, Atlas Bonus its purple), and the Scarab of Risk note moved into the breakdown as a normal row.',
      'Investment: the divine-price refresh now sits inside the price field; the Session-costs box matches the price field\'s surface (and drops the orange number); the scarab-preset save is a proper labeled icon button attached to the name field (Enter also saves); preset deletion and the reset-all-costs control use the standard destructive style; the Scarabs divider is centered.',
      'Advanced Costs: the chisel, delirium-orb and astrolabe dropdowns now show the real item icons in their options and in the field itself.',
      'Fixed: small item icons (scarab slots, cost chips, dropdowns) looked pixelated — they were force-rendered with nearest-neighbor scaling; they now downscale smoothly.',
      'Strategy Browser: the expanded card\'s stat grid uses the same boxed tiles as the Dashboard\'s Map Multipliers (no more free-floating numbers); tag and item badges are slightly bigger; the header buttons, refresh and count badge follow the standard button styles; Atlas Tree / View in Discord are visible bordered buttons instead of appearing only on hover.',
      'Dashboard: the loot Breakdown view got boxed category rows with a share-of-total percentage and thicker bars; the Baseline/Return buttons use a softer tint when set; the bottom total-value badges are slightly bigger.',
      'The check-for-updates button moved from the far corner to sit next to the version number in the title bar.',
      'Fresh coat of paint, part 3 — global readability pass: text sizes across every panel were lifted 1-2px onto one consistent scale (the small labels, stat values and mono regex lines were running below the rest of the app), and item icons got bigger everywhere — loot table rows, the chisel/deli/astrolabe cost chips, scarab pickers, and strategy-card badges.',
      'Strategy Browser: column widths re-tuned so Invest/Profit values no longer crowd each other, and the blue "own strategy" marker now reserves its slot permanently — rows stay aligned whether or not the marker shows.',
      'Regex Builder: the K-of-N section is now collapsible like the Alt/Aug section below it.',
      'The Analyse-a-Discord-Export view now shows real item icons on the chisel / delirium orb / astrolabe badges instead of the last remaining emoji.',
      'Scrollbars on native panels now stay hidden until you hover the scrolling area — less visual noise on unfocused panels.',
      'New League selector under the Divine Price (Investment panel): leave it on Auto to keep the poe.ninja auto-detection, or pick a league manually — e.g. when you are mapping in the parent league while an event runs, or after an event ends but detection still reports it. The choice sticks across restarts, drives prices, trade links and the Strategy Browser default filter, and the league list comes from poe.ninja (with a built-in fallback).',
      'Groundwork for the 3.29 league change: shared strategies now carry a small compatibility marker. Once 3.29 lands, a strategy that uses a scarab which was renamed, reworked or removed will show a yellow/red warning badge (with the specific item struck through in the expanded card), so you can tell at a glance whether an old shared strategy still works. Nothing shows yet — it activates automatically when the new patch data arrives.',
      'Groundwork for the 3.29 league change: the Atlas Tree panel now shows a small version badge when a loaded tree was built for a different game patch than the current one, so imported trees that predate a patch are easy to spot. Also dormant until the patch data updates.',
      'Clipboard capture now only polls while the Capture toggle is ON, instead of running constantly in the background. Turning Capture on also re-arms detection, so a map that was already in your clipboard from before the toggle is captured immediately — previously it was silently skipped as "identical content". (Running the same map twice in a row while capturing still needs the Paste button.)',
      'New optional Dashboard row — "Pace (estimate)": maps/hour and active time, derived locally from the time between your parsed maps (break-like gaps are excluded). Appears once 5+ maps carry timestamps; it is a rough estimate, is never shared, and div/map remains the real comparison metric.',
      'Loot icons during events now also pull the parent league\'s economy (e.g. Mirage while the Ancestors event runs), so far more items resolve to an icon while event economies are still thin.',
      'Performance: typing in Notes and toggling capture no longer re-serializes the entire store to disk on every keystroke — saving is now batched (max once per second, always flushed on close). Fixes the daily typing lag with many saved sessions.',
      'IMPORTANT — shared strategy numbers were previously wrong in some sessions: the Discord export disagreed with the Dashboard when a Preservation scarab was slotted (all scarabs were counted per-map), when a gem buy offset was configured (applied even without a baseline), or when investment neutralisation was active (omitted from the export). All profit math now lives in one shared module, so the export always matches the Dashboard exactly.',
      'IMPORTANT — Cost/map now means the ALL-IN figure everywhere: total investment divided by maps run. The Investment badge, the export Per Map Cost line, and the Strategy Browser all show the same number. The Strategy Browser derives it client-side from Total Invest / maps, which retroactively fixes the misleading low cost/map shown on ALL previously stored strategies.',
      'Fixed: session costs from Advanced Costs (delirium orbs per map etc.) no longer go stale — the total is now derived live from your settings and current map count, instead of freezing at the map count of your last Advanced Costs edit. Investment labels renamed to "Session costs" / "Session costs (total)" to match.',
      'Atlas Calc, Dashboard, Investment and the Share export now all use the same multiplier and cost formulas from one tested module — the three previously diverging copies are gone.',
      'Divination Cards are now their own map stat: the Divination chisel and "more Divination Cards" rolls feed a dedicated Div Cards tile on the Dashboard (hidden at 0) instead of being lumped into Currency.',
      'Strategy card cost breakdown: chisel line now displays for exports using the current "(Nc)" price format (previously only the old "(Nc each)" format matched, so chisel never showed). Breakdown relabeled "Base + session" / "= All-in".',
      'Fixed: the v13-to-v14 settings migration (mirageBonus to Atlas Bonus rename) never actually carried the value over — the defaults-fill ran first and made the carry dead code, so anyone updating from a pre-May version silently lost their Atlas Bonus toggle. The carry now runs before the fill, and the whole migration path is covered by tests.',
      'Loaded sessions now AUTO-SAVE: while a saved session is active, every change (maps, loot, costs, notes) is saved into it automatically — loading another session or closing the app can no longer silently discard your work. The Update button is gone; "Save as New" remains the way to fork a session.',
      'Deleting a session (row trash icon or the Delete button) now asks for confirmation — previously a single misclick next to Load destroyed a session permanently.',
      'Map Log now shows Name and Tier columns, so the name filter box no longer filters blind.',
      'Map Log now also has a Div column, showing each map\'s "more Divination Cards" roll alongside the existing Curr / Maps / Scarabs columns (shows "-" when the map had no such roll).',
      'Share modal: the astrolabe reminder is now editable — fix the count you actually used right there before copying to Discord, and the export preview updates live (the price still comes from Advanced Costs). Shows whenever an astrolabe type is set.',
      'Clearer wording: "Import Strategy" / "Share Strategy" (Discord) vs "Restore Sessions" (JSON backup) — same labels in the Sessions panel and Strategy Browser. The legacy Statistics and Loot panels are no longer offered in "+ Add Panel" (existing layouts keep working).',
      'Existing layouts: the leftover "Regex Builder" tab (from when it was merged into the "Regex" panel) is now cleaned up on its own — dropped if you already have a Regex tab, otherwise relabeled to Regex. Fresh/reset layouts were already clean; no more closing the duplicate by hand.',
      'Divine price now auto-refreshes when it goes stale (older than 30 minutes) instead of only when it was never set — a price typed in by hand counts as fresh and is never overwritten. A small "price: <league>" cue appears next to the Divine Price when the fetched price belongs to a different league than the current one.',
      'Atlas Tree: when reading node stats fails repeatedly, the error now says pathofpathing may have changed its layout and asks you to report it — instead of only suggesting you navigate the tree.',
      'Atlas Tree: if the tree ever drifts off-screen or looks black after you pan around or resize/maximize the panel, the Reload button re-centers it — now spelled out in its tooltip. (pathofpathing keeps its view position across resizes, so a reload snaps the view back to the tree.)',
      'Fixed: items missing from the poe.ninja icon cache (e.g. Forbidden Flame/Flesh) were shown with a WRONG icon (often a Chaos Orb) because of an over-eager partial-name match. They now show no icon instead — a blank is better than a lie.',
      'Fresh coat of paint, part 1: every icon in the app is now from a single consistent icon set (Tabler — Mantine\'s official pairing), and the mismatched emoji (⚙ 🪨 🌫 🔒 👥 📦 etc.) are gone from buttons and badges.',
      'Clearer Dashboard wording: the investment double-count banner now explains in plain language what happened and what the fix does ("Correct double-count" instead of "Neutralise"); the Baseline/Return buttons explain which CSV goes where.',
      'The investment double-count banner can now be reopened after dismissing it: if you click "These weren\'t double-counted" but the same items are still detected in the loot diff (e.g. after re-importing a return CSV), a small "Recheck" link brings the banner back. Previously dismissing it hid the check for the rest of the session.',
      'Version number now comes from one place — no more "UpdateBanner says 1.0.61 but the app is 1.0.62" class of bug.',
      'Fresh coat of paint, part 2: real Path of Exile item icons on game-item badges — your scarab picks in the Investment panel, and the chisel / delirium orb / astrolabe / scarab badges everywhere (Investment, Dashboard, Strategy Browser cards). Icons come from the poe.ninja cache; unknown items simply show no icon.',
      'Tests: profit, export and CSV-diff math now locked by fixture tests built from real clipboards, real WealthyExile exports and real v1.0.62 Discord exports.',
      'Importing a shared strategy from Discord is now decoration-proof: a pasted export reads the same whether it carries emoji, custom server emotes, or no icons at all, since import keys on the text labels rather than the icons.',
    ],
  },
  {
    version: '1.0.62',
    date: '2026-06-26',
    changes: [
      'Leagues: added the Return of the Ancestors event to league auto-detection and the Strategy Browser filter. Standard is no longer used as a detection fallback.',
      'Leagues: trade searches and the league display now follow the detected current league everywhere, removing the hardcoded "Mirage" fallback.',
      'Atlas Calc: Atlas Bonus (+25% IIQ, Quantity only) is now a toggle in the Atlas Calc panel. It defaults off on new sessions; turn it on once all 100 Atlas bonus objectives are complete.',
      'Atlas Calc: fixed the setup wizard skipping its remaining steps after a Yes answer, and not restarting on New Session.',
      'Atlas Tree: now resets to a blank tree when you start a New Session, instead of keeping the previously selected nodes.',
      'Atlas Tree: fixed the stats panel occasionally staying open after auto-reading an empty tree.',
      'Strategy Browser: the league filter now defaults to the newest league/event instead of Mirage.',
      'Strategy Browser: Load Build Settings from a Discord import now also applies scarabs (with costs), the atlas tree, and the chisel; previously it only loaded delirium orbs and astrolabes.',
      'poe.ninja: updated for the PoE1/PoE2 site split - the economy endpoints the app relied on had moved, which had broken the live divine price, league auto-detection, and loot icons. All now fetch through the app (more robust, no dev/CORS issues) and work again.',
      'Loot icons: restored across currency, fragments, scarabs, essences, uniques, maps, gems and more. Divination cards and any item poe.ninja does not index fall back to a generic icon instead of a blank.',
      'Privacy: strategy sharing no longer stores or transmits Discord avatar URLs - attribution still works via your Discord name and the message jump link.',
    ],
  },
  {
    version: '1.0.61',
    date: '2026-05-07',
    changes: [
      'Phase 4: Gem buy-back (gemBuyOffset) no longer added to profit when no baseline is set — it was inflating the return figure without a diff to neutralise.',
      'Phase 4: Brick mod fixes — ditio → 1 add (was matching all "additional" mods), max fr/ax end/ax pow → m f/m end/m po (abbreviated display assumption was wrong), tunn a → n sp (was not present in mod text), ax R in uber mods → 20% t. Known overlaps documented.',
      'Phase 4: AtlasTree webview now blocks off-domain navigation via will-navigate listener.',
      'Phase 4: AtlasTree auto-apply replaced flat 1500ms timeout with pollUntil — fires as soon as the stats button is rendered.',
      'Phase 4: AtlasTree silent catch{} replaced with console.error for stats-panel-close failures.',
      'Phase 4: Store migration v14→v15 — investmentNeutralization === -1 sentinel replaced with explicit investmentDismissed: boolean field.',
      'Phase 4: Investment detection normalises both sides with NFKD + apostrophe unification before matching — fixes misses on WealthyExile exports with curly apostrophes.',
      'Phase 5: rawText stripped from MapData on save — large per-map clipboard strings no longer accumulate in localStorage.',
      'Phase 5: Sessions panel now shows a Storage row with session count and MB used; turns orange above 4MB.',
      'Phase 5: localStorage quota errors now surface as a dismissible orange banner instead of silently failing.',
      'Phase 6: StrategyBrowserModule extracted from 59KB → 17KB. New files: utils/parseDiscordExport.ts (pure parser + 25 tests), utils/strategyConstants.ts (types + constants), components/StrategyCard.tsx, components/ShareModal.tsx, components/ImportModal.tsx.',
      'Phase 6: ImportModal now has a Load Build Settings button — apply chisel, deli orbs, astrolabe and regex from any pasted Discord export without it being on the server.',
      'Refactor: parseLootCsv and diffLootItems extracted from DashboardModule into utils/lootUtils.ts with 22 tests covering CSV edge cases and diff logic.',
      'Phase 7: Map Log filter — TextInput above the map table filters rows by name in real time, with a clear button and a \'X shown\' count.',
      'Phase 7: WealthyExile link in loot empty state — explains the export flow (log in, pick tabs, sync, ··· → Export CSV) with a clickable link.',
      'Phase 7: Brick mod IPC failure now surfaces an orange Alert in the Regex panel instead of silently staying on Loading… forever.',
      'Phase 7: Strategy Browser \'by you\' indicator — set your Discord tag once in the Share modal; your own strategies get a subtle blue left border and tint.',
      'Phase 7: Strategy card cost breakdown — expanded cards now show Base map / Chisel / Scarabs split when the data is available.',
      'Phase 7: Session bulk management — checkboxes on all history rows, Export selected as JSON, Delete selected with confirmation, Import JSON with conflict skip/overwrite choice.',
      'Regex: token consolidation — all stash regex tokens now live in modTokens.ts (single source of truth). RegexBuilder imports from it; BRICK_MOD_DEFS aligned. 28 divergent nightmare tokens fixed to in-game verified values.',
      'Regex: fixed broken "ax R" token for -20% Max Resistances — stash searches now correctly match this mod.',
      'Regex: removed dead regexToken field from uberMapMods.ts (was never consumed).',
    ],
  },
  {
    version: '1.0.59',
    date: '2026-05-01',
    changes: [
      'Trade: fixed Listed Status — was using \'available\' (Instant Buyout & In Person) instead of \'securable\' (Instant Buyout only). Searches now open on strictly Instant Buyout listings as intended.',
      'Trade: 8-mod map searches now include a # Modifiers ≥ 8 pseudo filter — previously selecting 8-mod did not strictly enforce 8 affixes, so sub-8-mod maps could appear in results.',
      'Loot categories: Vaal Gems were miscategorised as Currency — now correctly classified as Gems (e.g. Vaal Orb, Vaal Haste, Vaal Discipline no longer inflate the Currency loot line).',
      'Map parser: tier extraction on magic-rarity maps fixed — words between \'Map\' and \'(Tier N)\' no longer break tier detection.',
      'Map parser: Nightmare corruption detection logic corrected.',
      'Atlas Calc: 8-mod auto-detect now includes uncorrupted Nightmare maps — previously only corrupted maps triggered 8-mod mode.',
      'Atlas Tree: fixed auto-apply firing with onClick instead of a proper arrow wrapper — no longer double-fires on click.',
    ],
  },
  {
    version: '1.0.58',
    date: '2026-04-28',
    changes: [
      'Strategy server: switched to HTTPS — DEFAULT_API_URL is now https://wledger.richardpruett.com',
      'poe.ninja: divine price fetch now has a 60-second cooldown — if the network was offline and the price stayed at 0, the app no longer hammers poe.ninja on every InvestmentModule remount',
      'poe.ninja: manual refresh button bypasses the cooldown so explicit user action is never silently skipped',
      'poe.ninja: divine price and league detection both have a 5-second AbortController timeout — a hung response can no longer stall the app indefinitely',
      'Cleanup: deleted stale duplicate utils/useSessionStore.ts (the live store lives in store/useSessionStore.ts)',
      'Cleanup: deleted unused WelcomeModule (not registered, not in default layout)',
      'Cleanup: deprecated Statistics and Loot panels — bodies replaced with a notice pointing at Dashboard, since their old math was missing recent corrections (Atlas Bonus, gem-buy offset, investment neutralisation). Panels stay in the registry so old saved layouts don\'t show "Unknown Module"',
      'Build: moved @types/uuid from dependencies to devDependencies',
    ],
  },
  {
    version: '1.0.57',
    date: '2026-04-26',
    changes: [
      'Investment: Preservation is now fully automatic — when any slot contains a Preservation scarab, all other scarabs are treated as one-time cost, no manual toggle needed',
      'Investment: 🔒 preservation active indicator appears next to the Scarabs header with a tooltip explaining the logic',
      'Investment: scarab slot UI restored to original clean layout with no extra controls',
    ],
  },
  {
    version: '1.0.56',
    date: '2026-04-26',
    changes: [
      'Investment: Preservation toggle per scarab slot — toggle to mark a scarab as preserved (kept by Horned Scarab of Preservation)',
      'Investment: preserved scarabs are treated as one-time cost instead of per-map cost — only Preservation scarab itself is counted per-map',
      'Investment: 🔒 Preserved Xc badge shown in cost indicators when any scarab is marked preserved',
      'Dashboard: investment auto-detection — after importing both baseline and return, detects if configured investment items (scarabs, astrolabes, deli orbs) appear in the diff losses',
      'Dashboard: yellow warning banner shows matched items with their loss values and a Neutralise button',
      'Dashboard: neutralising adds the loss values back to loot gain to un-do the double-count from having investment in tracked stash tabs at baseline time',
      'Dashboard: neutralisation can be undone and resets on new session',
    ],
  },
  {
    version: '1.0.55',
    date: '2026-04-26',
    changes: [
      'Scarab list: updated to 111 verified droppable scarabs for Mirage League (3.28)',
      'Removed: Scarab of Bisection (split into Sinistral/Dextral in 3.28), Sinistral/Dextral Breach Scarab (never real items)',
      'Removed: all Shrine Scarab variants (no such scarabs exist), Ritual Scarab plain, Scarab of Hunted Traitors (drop-disabled)',
      'Removed: plain Breach Scarab, Cartography Scarab, Divination Scarab (not droppable in current league)',
      'Added: Breach Scarab of Resonant Cascade, Breach Scarab of the Marshal, Divination Scarab of Pilfering, Horned Scarab of Awakening, Scarab of Radiant Storms, Incursion Scarab of Timelines and others',
    ],
  },
  {
    version: '1.0.54',
    date: '2026-04-26',
    changes: [
      'Atlas Calc: wizard no longer skips when a blank pathofpathing tree is loaded — pathofpathing emits a hash even for an empty tree which was incorrectly treated as configured',
      'Atlas Calc: wizard visibility now derived purely from actual calc settings (mounting, fragments, nodes) and the dismissed flag',
      'Atlas Calc: wizard resets correctly on every New Session — dismissed flag cleared, step back to mounting',
      'Atlas Calc: pill editing state clears automatically when settings are applied externally (Load Build Settings)',
      'Atlas Calc: added Skip button with tooltip — skips wizard and shows pills immediately',
      'Atlas Tree: New Session no longer triggers stat reading or leaves the stats panel open',
    ],
  },
  {
    version: '1.0.53',
    date: '2026-04-26',
    changes: [
      'Strategy Browser: group/party play support — solo is the default assumption, no tag needed',
      'Share modal: Party Play toggle — when enabled adds "👥 Party Play: Yes" to the export',
      'Strategy Browser: group strategies show a 👥 cyan badge next to the author name with tooltip',
      'Strategy Browser: 👥 filter toggle in the filter row — click to hide group play strategies and see solo-only',
      'Parser: Party Play: Yes detected from raw_export for backward compatibility with existing strategies',
      'Server: is_group_play column added to strategies table — requires a one-time database migration',
    ],
  },
  {
    version: '1.0.52',
    date: '2026-04-26',
    changes: [
      'Brick exclusions: fixed 6 broken/suboptimal regexTerms in BRICK_MOD_DEFS',
      'triple → oral (Triple Curse — "triple" matched nothing in any map mod text)',
      'ess def → fenc (Less Defences — "ess def" never appears in the mod text)',
      'o al → ax R (Reduced Max Res — o al hit Afflicting/Conflagrating)',
      'ossesse → poss (Possessed), uffs on → yers e (Buffs Expire), enetr → net (Penetrates)',
      'Map Analyzer: mod detection now uses multi-line keyword matching — mods with 2+ effect lines are now correctly identified',
      'Map Analyzer: complete uber + top-tier mod pools from authoritative JSON sources',
    ],
  },
  {
    version: '1.0.51',
    date: '2026-04-25',
    changes: [
      'Fixed: ax R replaces all m (Max Res) — all m was matching Afflicting+Conflagrating ("All Monster Damage"); ax R from m**ax R**esistances is unique',
      'Fixed: ter Mo replaces veme (Fleet) — veme was matching Juggernaut+Unstoppable ("Monsters\u2019 Movement Speed"); ter Mo requires space-before-M which Monsters\u2019 (apostrophe) never provides',
      'uberMapMods.ts: fully rewritten from authoritative uber_tier.json — all mods present, all effect lines complete, correct bonuses',
      'regularMapMods.ts: fully rewritten from authoritative top_tier.json — complete mod pool with all effect lines that were previously missing',
      'Both mod files now have verified regexToken fields where applicable',
    ],
  },
  {
    version: '1.0.50',
    date: '2026-04-25',
    changes: [
      'Fixed: all m replaces -20 (Max Res both groups) — -20 was matching top tier "-20% to amount of Suppressed Spell Damage Prevented"; "all m" from "to all maximum" avoids this',
      'Fixed: veme replaces eme (Fleet/Movement) — eme matched anything containing "Elemental" (12 overlaps); "Elemental" has no v so "veme" from "movement" is clean',
      'Fixed: oral replaces mpor (Triple Curse) — mpor matched "Temporarily Revive" ("Tempora**r**ily"); "oral" from "Temp**oral** Chains" is distinct (r vs l at position 4)',
      'Fixed: a Ma replaces gy S (Extra ES) — gy S matched any mod with Energy Shield text (5 overlaps); only "Extra Maximum" contains the sequence a-space-M-a',
      'Fixed: m End replaces dura (Endurance Charges) — dura matched Poison Duration + top-tier Endurance mods; "m End" from "Maximum End**urance" avoids "Maximum Ene**rgy" (e not d)',
    ],
  },
  {
    version: '1.0.49',
    date: '2026-04-25',
    changes: [
      'Regex Builder: full collision audit against both uber AND top-tier originator mod pools',
      'Fixed: -t replaces hap (Shaper-Touched, saves 1 char)',
      'Fixed: -20 replaces o al (Max Res, both occurrences — uniquely targets -20% uber vs -12 to -9% top tier)',
      'Fixed: deb replaces xpi (of Defiance — xpi was also matching Buffs on Players expire)',
      'Fixed: k d replaces k a (Stalwart — k a collided with Attack and Cast Speed)',
      'Fixed: t 20 replaces f p (Punishing — reflects 20% vs top tier 18%, now unique)',
      'Fixed: eme replaces nt s (Fleet — nt s was matching Juggernaut Action Speed line; eme from movement is not in Action Speed)',
      'Fixed: az replaces nth (Labyrinth — nth collided with Synthetic/Synthesis Boss top tier)',
      'Fixed: n ig replaces nite (Afflicting — n ig from can ignite vs top tier chance to/always ignites)',
      'Fixed: mpor replaces uln (Triple Curse — Temporal Chains is unique to uber; top tier only has Vulnerability)',
      'Fixed: gy S replaces as Ex (Extra ES — as Ex matched Extra Chaos and Extra Elemental too)',
      'Fixed: mum f replaces renzy (Frenzy Charges — renzy matched of Enervation steals-charges mod)',
      'Fixed: dura replaces mum e (Endurance — mum e collided with Maximum Energy Shield)',
      'Noted: tun, poss, 2 a, ter D, yers e, o su, uct have unavoidable top-tier overlaps (same mod text, different stats)',
    ],
  },
  {
    version: '1.0.48',
    date: '2026-04-25',
    changes: [
      'Regex Builder: 5 more token compressions — 2 a (AoE), oss (Possessed), net (Penetrates), uct (PDR), um p (Power Charges)',
      'Regex Builder: tooltips now dark-themed with border, matching app aesthetic; token shown as bold monospace pill; no redundant label repetition',
      'Regex Builder: \'At least X\' control bar given distinct dark green background to visually separate from mod list above it',
      'Regex Builder: per-group regex preview now in a distinct dark inset block',
      'Regex Builder: \'How this works\' collapsed by default — click to expand; power users know it, first-timers can discover it',
      'Regex Builder: \'Giga currency\' renamed to \'Currency Floor (Ignore Pack Size)\' for clarity',
    ],
  },
  {
    version: '1.0.47',
    date: '2026-04-24',
    changes: [
      'Regex Builder: maximum token compression pass — all tokens reduced to absolute minimum unique length',
      'Saves up to 3-5 chars per token, enabling significantly more complex K-of-N combinations before hitting 250-char limit',
      'lid(3) chain, ssed(4) possessed, rea o(5) AoE, ter D(5) monster damage, nt s(4) speed, o al(4) max res, enet(4) penetrates',
      'nite(4) ignite/freeze, vol(3) volatile, uln(3) vulnerability, fenc(4) defences, rasp(4) grasping, as Ex(5) extra ES',
      'o su(4) suppress, duct(4) reduction, mum p(5) power charges',
      'xpi(3) expire, k a(3) block attack, f p(3) reflect phys, tun(3) stunned, eor(3) meteor',
    ],
  },
  {
    version: '1.0.46',
    date: '2026-04-24',
    changes: [
      'Regex Builder: all mod groups now start with nothing selected — click to pick your mods',
      'Regex Builder: Regex Builder tab added to default layout next to Regex (users with saved layouts can drag it there manually or reset layout to default)',
      'Regex Builder: Shaper-Touched tooltip cleaned up',
      'Regex Builder: applied research SUS token improvements — mav (3), nth (3), rke (3), ne b (4), vola (4), teor (4), et sp (5), yers e (6) replacing longer previous tokens',
      'Regex Builder: Maps mods tokens all shortened — as Extr, ppress, educt, ower C, renzy, mum e, ne b replacing 10-17 char tokens',
    ],
  },
  {
    version: '1.0.45',
    date: '2026-04-24',
    changes: [
      'Regex Builder: tooltip token display fixed — no longer dark-on-dark, uses monospace with explicit light colour',
      'Regex Builder: all labels now use actual in-game mod text (e.g. Fecund — More Monster Life 90-100%, not High Life)',
      'Regex Builder: pack size mods now show their pack% bonus in the label (e.g. Shaper-Touched +20% pack)',
      'Regex Builder: Flask Effect label simplified to just show the secondary reward (+47%), penalty implicit in mod name',
      'Regex Builder: group labels show actual counts dynamically — removed hardcoded “5 Uber Mods” text',
      'Regex Builder: added Quantity Mods, Scarab Mods, and Maps Mods preset groups',
      'Regex Builder: Alt/Aug chisel toggle now directly adjusts the number boxes (±50) so the displayed value is always what\'s being searched',
      'Regex Builder: pack size default selection is the 4 Horsemen only (not all mods)',
    ],
  },
  {
    version: '1.0.44',
    date: '2026-04-24',
    changes: [
      'Regex Builder: all currency mod labels corrected — Stalwart (k at), Punishing (f ph), Diluted (sks), Ultimate (wb), of Defiance (xpir), Juggernaut (tunn), of Imbibing (eteor)',
      'Regex Builder: of Defiance (64% Currency, Debuffs expire faster) added as S-tier — was missing entirely from the preset',
      'Regex Builder: Juggernaut (Cannot be Stunned, 47% Currency) and of Imbibing (Meteor Flask, 45% Currency) added to currency pool',
      'Regex Builder: Alt/Aug crafting now uses ^Map of (confirmed working in PoE!) for suffix-only detection — prefix/suffix toggle removed, both patterns combined cover all cases with zero false positives',
      'Regex Builder: Alt/Aug explained: prefix-only map detected by " Map (Tier", suffix-only by "^Map of", full 2-mod map matches neither — stays dark correctly',
      'uberMapMods.ts: comprehensive update from full pasted mod pool — all mods, correct quant/rarity/pack values, verified tokens',
      'uberMapMods.ts: added Ultimate (Bloodstained Sawblades, 47% Currency) which was missing',
      'uberMapMods.ts: added regexToken field to every mod for direct stash regex use',
    ],
  },
  {
    version: '1.0.43',
    date: '2026-04-24',
    changes: [
      'Regex Builder: removed Originator Search preset as unnecessary',
      'Regex Builder: Quick Reference moved into mod badge tooltips — hover any mod for full text, token, and description',
      'Regex Builder: Alt/Aug crafting is now fully dynamic — adjustable currency min, pack size min, and giga-currency threshold',
      'Regex Builder: Avarice chisel toggle — when not yet applied, thresholds are lowered by 50 to match pre-chisel roll values',
      'Regex Builder: currency mod position toggle (Prefix vs Suffix) controls which open-slot pattern is used in gate 2',
      'Regex Builder: mod tooltips show full in-game mod text, regex token, and why the token was chosen to avoid false positives',
      'Regex Builder: currency mod labels marked [verify] where exact in-game mod name is uncertain — update once confirmed in game',
    ],
  },
  {
    version: '1.0.42',
    date: '2026-04-24',
    changes: [
      'New panel: Regex Builder — K-of-N combinatorial stash regex generator using Product of Sums logic',
      'Regex Builder: pick mods from preset groups (4 Horsemen packsize, 5 uber currency mods), set minimum K, generates correct AND-block regex automatically',
      'Regex Builder: supports multiple groups AND\'d together (e.g. 2 packsize AND 2 currency in one string)',
      'Regex Builder: custom token input for any mod not in the presets',
      'Regex Builder: live character count with 250-char PoE stash limit warning',
      'Regex Builder: crafting presets — Alt/Aug magic map crafting, 2+2 dual-gate, 3+2 god-tier, Originator search',
      'Strategy Browser: league filter now defaults to Mirage and reads from KNOWN_LEAGUES in league.ts',
      'Strategy Browser: hardcoded old league list removed — update league.ts to add future leagues',
    ],
  },
  {
    version: '1.0.41',
    date: '2026-04-24',
    changes: [
      'Atlas Tree: New Session no longer triggers atlas tree stat reading or leaves the pathofpathing stats panel open',
      'Atlas Tree: stats panel is now closed automatically when switching sessions',
      'League: simplified to Mirage only — removed Dawn of the Hunt, Settlers, Standard etc. from probe list',
      'League: easy to extend for future leagues — just update CURRENT_LEAGUE and KNOWN_LEAGUES at the top of league.ts',
      'Regex: fixed double-exclusion bug (“!”!…””) caused by corrupted regexExclusions containing full regex strings instead of bare terms',
      'Regex: sanitizeExclusionTerms() added — strips quotes, leading !, and rejects any term with special regex characters',
      'Regex: migration cleans corrupted regexExclusions and defaultExclusionPreset in all saved sessions on next load',
      'Regex: trade window regex now includes rarity (IIR) in the generated Copy Regex',
      'Atlas Calc: wizard now reactively watches settings values — no longer shows yes/no questions after Load Build Settings applies calc data asynchronously',
    ],
  },
  {
    version: '1.0.40',
    date: '2026-04-22',
    changes: [
      'Regex: fixed thresholdPat for currency floors 100–199 — e.g. 140% now correctly generates 1[4-9].|[2-9].. instead of the ambiguous \\d.. pattern',
      'Regex: removed “⚠ Open slot only for slam” note',
      'Trade: trade modal stays open after clicking Search so you can adjust filters and re-search',
      'Trade: Copy Regex button has fixed minimum width so it doesn’t resize when showing Copied',
      'Changelog: past versions are now collapsible — click any version header to expand its changes',
      'Tags: removed Titanic (not a meaningful build mechanic), restored Ambush (= Strongboxes, still in game)',
      'Types: removed sinistral/dextral from RegexSet type',
      'Trade: Shaper/Elder influenced and Conqueror-occupied maps are now always excluded from results',
      'Security: Atlas Tree and Atlas Calc URL checks now use proper hostname parsing, fixing all CodeQL high-severity alerts',
      'Suppress mods: split into three correct separate entries with accurate API needles',
    ],
  },
  {
    version: '1.0.39',
    date: '2026-04-21',
    changes: [
      'Strategy Browser: column layout overhauled — uniform gap spacing between all columns, consistent alignment across header and rows',
      'Strategy Browser: added Cost/map column showing per-map investment cost',
      'Strategy Browser: renamed Invest → Total Invest, Profit → Total Profit',
      'Strategy Browser: Author / Strategy header shortened to Author',
      'Strategy Browser: number formatting strips trailing .0 from k-values (107.0kc → 107kc, 3.6kc stays 3.6kc)',
      'Strategy Browser: Tags column widened to 140px with uniform 6px column gap for better 3-tag display',
      'Strategy Browser: tag abbreviations limited to genuinely compound names only (emp+orig, deli, astrolabe variants, boss, mirage) — all others kept as full names',
      'Strategy Browser: removed Harbinger and Metamorph from tag options (no longer in the game)',
      'Strategy Browser: Profit/map falls back to net_profit ÷ divine_price ÷ map_count when server stored null',
      'Strategy Browser: Discord export renamed Profit/map back to Div / Map to match server bot parser',
      'App: panel layout now persists across restarts — panels remember their position, size and which are open',
      'App: Reset layout to default option added to the + Add Panel menu',
    ],
  },
  {
    version: '1.0.38',
    date: '2026-04-20',
    changes: [
      'App: panel layout now persists across restarts — resize, reorder, and close panels and your layout is remembered',
      'App: “Reset layout to default” option added to the + Add Panel menu',
      'Strategy Browser: Profit/map now falls back to computing from net_profit ÷ divine_price ÷ map_count when the server stored it as null',
      'Strategy Browser: Tags column widened from 78px to 105px to comfortably show 3 tags',
      'Strategy Browser: Mod column has left padding so it no longer runs directly against the tags',
    ],
  },
  {
    version: '1.0.37',
    date: '2026-04-20',
    changes: [
      'Strategy Browser: 8-mod detection fixed — now uses the strategy\'s map_type field (6-mod/8-mod) instead of the content tag',
      'Strategy Browser: restored missing fallback for strategies without raw_export but with a stored run_regex',
      'Regex: paste preview field is now cleared automatically when switching sessions or loading a strategy',
      'Regex: reset button removed — the mod picker dropdown X button serves the same purpose',
      'Regex: Set Default button enlarged and renamed to “Set Default Preset” for clarity',
      'Regex: “Their exclusions” button renamed to “Show their exclusions ↑”',
    ],
  },
  {
    version: '1.0.33',
    date: '2026-04-19',
    changes: [
      'Trade: Instant Buyout fixed — status: available is the correct API value (confirmed via PoB URL inspection; online = In Person Online, available = Instant Buyout)',
      'Trade: Brick exclusion mod list now includes all monster-type mods (Inhabited by X, Increased Variety) and missing nightmare combined mods',
      'Regex: clearing the brick mod multiselect (X button) now clears ALL exclusions including custom terms',
      'Regex: paste preview shows full mod names instead of short terms — purple for nightmare, yellow for regular',
      'Strategy Browser: Load Build now populates a “Loaded from strategy” blue box in Regex with their averages and regex (with your exclusions applied)',
      'Strategy Browser: “Show their exclusions” button pastes the author’s original regex into the preview field so you can see what they were excluding',
      'Strategy Browser: Trade modal now pre-fills IIQ/IIR/Pack/Currency from the loaded strategy when no maps are parsed',
    ],
  },
  {
    version: '1.0.32',
    date: '2026-04-19',
    changes: [
      'Regex: new sessions start with no exclusions and no hardcoded fallback — generated regex is clean by default',
      'Regex: removed manual text entry field — replaced with regex paste preview that extracts exclusion terms and shows matched mods',
      'Regex: pasted regex terms matched to brick mod list with tooltips; Apply button adds them to exclusions',
      'Regex: brick exclusion ? tooltip reworded and fake mod examples removed',
      'Regex: nightmare mods coloured purple in both the brick exclusion picker and trade modal',
      'Strategy Browser: Load Build now saves the strategy run/slam regex as saved sets with your exclusions applied',
      'Trade: Instant Buyout fixed — status: online in the API query now correctly opens with Instant Buyout on the trade site',
      'Trade: Min Tier filter added (default 16) to exclude sub-T16 maps from results',
      'Trade: Corrupted override added — explicitly set Yes/No/Any independent of map type',
      'Trade: 0% delirium option added — requires the delirium enchant to be present at >=0%',
      'Trade: button label updated to show Instant Buyout is active',
    ],
  },
  {
    version: '1.0.31',
    date: '2026-04-19',
    changes: [
      // Regex — Brick Exclusion overhaul
      'Regex: Brick Exclusions now has a searchable mod picker (same full list as the Trade modal) — selecting a mod adds its short regex term to the chip list',
      'Regex: picking mods from the list and the chip list are fully bidirectional — deselecting a mod removes its term, removing a chip deselects the mod',
      'Regex: brick exclusion dropdown uses the same grouped data (Regular / Nightmare) as the Trade modal, computed once and shared',
      'Regex: Open Trade button is now always visible, not hidden when no maps are parsed',
      'Regex: new sessions start with empty brick exclusions — no pre-selected mods on a fresh session',
      'Regex: reset button clears all exclusions instead of restoring old hardcoded defaults',
      // Trade modal — brick exclusion sync
      'Trade: opening the trade modal auto-selects mods whose regexTerm is already in your brick exclusions',
      'Trade: → Sync to Regex Exclusions button pushes selected trade exclusions back as regex chip terms',
      'Trade: brick exclusion dropdown deduped by stat ID — no more Mantine duplicate options crash',
      // Map Analyzer tooltip
      'Map Analyzer: hover tooltip text colour fixed — explicit colour override prevents near-black text on dark background',
      // PoE Trade— mod list
      'Trade: brick mod definitions now include regexTerm for each of ~95 regular and nightmare map mods',
      'Trade: 8-mod map type now also excludes Originator maps (NOT originator implicit applied)',
    ],
  },
  {
    version: '1.0.30',
    date: '2026-04-19',
    changes: [
      // Map Analyzer
      'Map Analyzer: regular T16 maps now analysed with their own mod pool — separate from Originator/Uber mods',
      'Map Analyzer: grid auto-dispatches to correct analyser per map (isOriginator flag); Originator vs Regular T16 badge on tooltip + detail bar',
      'Map Analyzer: quality thresholds updated — Excellent = 4+ S/A mods (6 possible total, up from 3)',
      'Map Analyzer: multi-tab support — Tab 1/Tab 2 buttons appear when maps exceed the layout slot count',
      'Map Analyzer: Map Device layout auto-disabled when >20 maps are parsed',
      'Map Analyzer: chisel logic corrected — both Avarice and Proliferation bonuses are flat additive after the atlas multiplier, not multiplicative',
      // PoE Trade integration
      'Regex: "Open Trade" button opens a full search modal — map type (Regular/8-mod/Nightmare/Originator), Empowered Mirage toggle, Min IIQ/IIR/Pack, pseudo currency/scarabs/maps, delirium %, reward type multiselect',
      'Trade: delirium reward type uses OR logic (IF group) — map needs ANY of the selected types, not all',
      'Trade: delirium % filter correctly uses the enchant stat, not the explicit duplicate',
      'Trade: Originator implicit and Empowered enchant stat IDs fetched from PoE stats API at startup and cached; PoE2 groups skipped to avoid duplicates',
      'Trade: Nightmare type search uses NOT originator implicit + pseudo currency/scarabs/maps min to identify uber-mod maps',
      'Trade: modal auto-detects map type and empowered flag from your current parsed session',
      'Trade: pseudo stat IDs corrected to _currency_drops, _scarab_drops, _map_drops',
      'Regex: poe.re button removed — Open Trade replaces it',
    ],
  },
  {
    version: '1.0.27',
    date: '2026-04-18',
    changes: [
      'Regex: removed Sinistral/Dextral sections — 250-char limit makes them impractical',
      'Regex: poe.re button fixed (was 404), renamed to "Open poe.re", moved next to Save Run/Save Slam',
      'Map Analyzer: removed Sinistral/Dextral recommendation system and Paste tab',
      'Map Analyzer: grid now colors maps by quality tier (Excellent/Good/Decent/Standard based on S+A mod count)',
      'Map Analyzer: chisel recommendation (Avarice/Proliferation) shown as dot on each map cell and in detail bar',
      'Map Analyzer: summary badges now show quality tier counts and chisel counts',
    ],
  },
  {
    version: '1.0.26',
    date: '2026-04-18',
    changes: [
      'Fix: Excluded drops and Gem leveling lines restored to Discord export (were incorrectly removed in v1.0.25)',
      'Strategy Browser: Excluded drops now shown in expanded strategy card (parsed from raw export)',
      'Strategy Browser: Gem leveling now shown in expanded strategy card with buy/sell/net breakdown',
      'Import modal: Excluded drops and Gem leveling now shown when analysing a pasted export',
    ],
  },
  {
    version: '1.0.25',
    date: '2026-04-18',
    changes: [
      'Dashboard: Investment and Loot gain rows now show divine equivalent in grey (e.g. 158876c (491.88d))',
      'Atlas Calc: Atlas Bonus removed from the multiplier — it only affects Quantity, not all stats. Now shown as a separate note below the multiplier',
      'Dashboard: Quantity projection correctly adds the flat +25 IIQ from Atlas Bonus on top of the multiplier',
      'Strategy Browser: Invest and Profit columns now show divine sub-text in row and expanded card',
      'Strategy Browser: Div/map column renamed to Profit/map — the value is net profit in divines per map',
      'Discord export: removed Excluded drops and Gem leveling lines — app-internal info not relevant for strategy sharing',
      'Discord export: Build Type label renamed to Tags',
      'Discord export: Div / Map renamed to Profit/map',
      'Load Build: now correctly loads deli orb price, astrolabe count and price from raw export',
    ],
  },
  {
    version: '1.0.24',
    date: '2026-04-18',
    changes: [
      'Hotfix: bump store to v14 so mirageBonus → atlasBonus migration runs on existing sessions — Atlas Bonus now correctly preserved on update',
    ],
  },
  {
    version: '1.0.23',
    date: '2026-04-18',
    changes: [
      'Fix: Discord export now correctly accounts for baseline deduction and gem buy offset — Total Return and Net Profit now match the dashboard exactly',
      'Fix: Atlas Tree auto-apply no longer leaves the node stats overlay or pathofpathing stats panel open',
      'Renamed: "Mirage League" bonus is now labelled "Atlas Bonus" in Atlas Calc (field renamed atlasBonus)',
      'Strategy Browser: server URL field removed — server is now always the live endpoint',
    ],
  },
  {
    version: '1.0.22',
    date: '2026-04-17',
    changes: [
      'Strategy Browser: delirium orbs and astrolabe shown as headers in expanded strategy view',
      'Strategy Browser: Load Build Settings now also loads delirium orb type/qty and astrolabe type',
      'Strategy Browser: Import modal now shows deli orbs and astrolabe badges when present',
      'Share: astrolabe tag auto-added to build type tags when astrolabe is configured in Advanced Costs',
      'Investment: scarab cost field widened (was getting squished)',
      'Atlas Tree: auto-reads stats and applies to Atlas Calc after URL is imported or loaded from a build',
    ],
  },
  {
    version: '1.0.21',
    date: '2026-04-17',
    changes: [
      '8-mod auto-detect: now requires maps to be corrupted — Cartography Scarab of Risk no longer incorrectly flips sessions to 8-mod',
      'Discord export: delirium orbs now included (type, count, % delirious, cost/map)',
      'Discord export: slam regex omitted for 8-mod maps (corrupted maps cannot be exalted)',
      'Discord export: tag abbreviations in strategy list (emp+orig, a:enshr, etc.) — full name still shown on hover',
      'Dashboard: gem buy-back accounting — when gem name is configured and gems are excluded from loot CSV, buy cost is added back so gem activity is neutral to map profit',
      'Server (bot): incomplete exports now rejected — DM sent listing missing fields; message deleted from channel',
      'Server (bot): astrolabe tags auto-assigned from astrolabe type name in export',
      'Server (bot): delirium orbs parsed from export',
    ],
  },
  {
    version: '1.0.20',
    date: '2026-04-15',
    changes: [
      'Build fix: escaped quotes in Gem Leveling description',
      'Map subtype detection: sessions loaded from storage now re-detect Empowered Mirage / Originator from rawText — fixes wrong \'regular\' tag on old sessions',
      'Share: subtype tag detection uses rawText fallback for all maps, not just stored flags',
      'Discord export: slam regex suppressed for 8-mod maps (corrupted, can\'t exalt)',
      'Discord export: astrolabe line added when astrolabe is configured',
      'Share modal: teal alert when an astrolabe is set — prompts user to verify count before sharing',
      'Strategy Browser: astrolabe tags added (generic + per-type)',
      'Regex panel: 8-mod / Nightmare maps suppress slam with a note; poe.re button copies run regex and opens poe.re/maps',
      'Dashboard: baseline import tip explaining the investment double-dip risk',
    ],
  },
  {
    version: '1.0.19',
    date: '2026-04-15',
    changes: [
      'Gem Leveling: now tracks buy price + sell price separately — shows net gem P&L',
      'Gem Leveling: add gem name to auto-exclude matching items when a loot CSV is imported',
      'Gem Leveling: buy/sell/net breakdown shown in the Gem Leveling section of Advanced Costs',
      'Gem Leveling: export shows buy total, sell total, and net P&L as a separate note',
      'Gem badge now shows net P&L in green/red (positive/negative) instead of a flat total',
    ],
  },
  {
    version: '1.0.18',
    date: '2026-04-15',
    changes: [
      'Notes: now per-session — saved and loaded with each session, cleared on new session',
      'Gem leveling: removed from investment cost — it is side income, not a map expense',
      'Gem leveling: now shown as a separate violet “Side income” badge below investment costs',
      'Eater/Exarch tags: removed from scarab auto-detection (they are atlas tree nodes, not scarabs)',
      'Eater/Exarch: still correctly auto-detected from atlas tree node stats when you Read Stats',
    ],
  },
  {
    version: '1.0.17',
    date: '2026-04-15',
    changes: [
      'Regex: Brick Exclusions editor in Regex panel — add/remove terms, live preview, reset to defaults',
      'Regex: generated run/slam regex now uses your saved exclusion list',
    ],
  },
  {
    version: '1.0.16',
    date: '2026-04-14',
    changes: [
      'Notes tab restored: global scratchpad that persists across sessions (never cleared)',
      'Investment: Gem Leveling section in Advanced Costs — tracked separately from profit',
      'Export: excluded drops listed in the Discord export with names and values',
      'Export: gem leveling shown as optional income note when filled',
      'Share modal: warning when investment costs are 0',
      'Strategy Browser: map count column no longer shows "m" suffix',
      'Strategy Browser: Eater of Worlds + Searing Exarch tags added',
      'Atlas Tree: Eater/Exarch auto-detected from tree node group titles',
      'Atlas Calc: wizard now skips to done when a real tree URL is loaded (fixes Load Build Settings annoyance)',
      'Regex: exclusion list is now configurable per session ("regexExclusions" in settings)',
    ],
  },
  {
    version: '1.0.15',
    date: '2026-04-14',
    changes: [
      'Dashboard: multiplier now includes Mirage League +25% flat IIQ — was showing 0.25× less than Atlas Calc',
      'Strategy Browser: column headers now perfectly aligned with data rows',
      'Strategy Browser: Tags column wider (96px, 3 chips visible), better use of available space',
      'Strategy Browser: map-type tags (regular, originator, empowered etc.) now show tooltip on hover',
      'Sessions: Import on left, Share on right',
      'Atlas Tree: Apply to Calc button moved to toolbar (visible after Read Stats)',
      'App: version number shown in title bar next to WRAECLASTLEDGER',
    ],
  },
  {
    version: '1.0.14',
    date: '2026-04-14',
    changes: [
      'Strategy Browser: session notes field in Share modal — shown in the browser and import modal',
      'Atlas Tree: import URL button (📎) — paste any pathofpathing.com URL to load that tree',
      'Atlas Tree: “Apply to Calc” button in stats overlay auto-fills small nodes, Mounting Modifiers, fragments',
      'Sessions: panel now scrolls the entire card when history is long',
    ],
  },
  {
    version: '1.0.13',
    date: '2026-04-14',
    changes: [
      'Notes tab: per-session freeform notes saved with each session (Map Log tabset)',
      'Investment: clearer descriptions on Rolling Costs and Split Session sections',
      'Sessions: notes saved/loaded alongside maps and loot when using Save/Update/Load',
    ],
  },
  {
    version: '1.0.12',
    date: '2026-04-14',
    changes: [
      'Sessions: history list now properly scrolls when there are many sessions',
      'Sessions: Share and Import buttons added directly to the Sessions panel',
      'Investment: reset button (×) clears all costs while keeping divine price',
      'Atlas Calc: improved tooltip hints on Mounting Modifiers and Multiplying Modifiers',
    ],
  },
  {
    version: '1.0.11',
    date: '2026-04-14',
    changes: [
      'Sessions: Save as New no longer requires maps to be parsed',
      'Strategy Browser: Author column now shows strategy name (if set); tag column shows multi-tag chips with overflow tooltip',
      'Strategy Browser: Invest column now uses consistent fc() formatting matching Profit (e.g. 6.7kc)',
      'Strategy Browser: Date column hidden by default — click the ··· header to toggle it back on',
      'Strategy Browser: map subtype tags added (regular, originator, empowered, empowered-originator, nightmare, mixed)',
      'Strategy Browser: Share modal auto-detects map subtype from parsed maps + merges atlas tree tags',
      'Atlas Tree: reading stats now infers strategy tags from allocated node group titles (Delirium, Beyond etc.)',
    ],
  },
  {
    version: '1.0.10',
    date: '2026-04-14',
    changes: [
      'Map parser: Strategy Browser now appears as a default tab next to Map Log — no more manual adding',
      'Map parser: fixed mod count for corrupted and Nightmare maps — 8-mod detection now correct',
      'Map parser: detects Originator maps, Empowered Mirage maps, Nightmare maps, and corrupted maps',
      'Map parser: strips PoE color tags (<tag>{content}) before parsing — corrupted map mods now parse correctly',
      'Map parser: all four detection fields stored per map for future statistics use',
    ],
  },
  {
    version: '1.0.9',
    date: '2026-04-14',
    changes: [
      'Strategy Browser: multi-select type tag filter — filter by Delirium + Beyond + Legion simultaneously',
      'Strategy Browser: league filter — show only Mirage / Dawn of the Hunt / etc. strategies',
      'Discord export: league name included automatically (auto-detected from poe.ninja on startup)',
      'Atlas Calc: map type auto-detected from parsed maps — switches 6-mod ↔ 8-mod when ≥4 maps confirm it',
    ],
  },
  {
    version: '1.0.8',
    date: '2026-04-14',
    changes: [
      'Atlas Tree: Read Stats now captures ALL node groups (Beyond, Delirium, Shrines etc.) — fixed lazy-render issue',
      'Atlas Calc: Mirage League +25% flat IIQ bonus toggle — on by default, turns off next league',
      'Strategy Browser: time period filter — All time / Last 24h / 3 days / 7 days',
      'Strategy Browser: Boss Rush and Mirage Rush added as strategy type tags',
      'Strategy Browser: multiplier export now includes Mirage League bonus when active',
    ],
  },
  {
    version: '1.0.7',
    date: '2026-04-14',
    changes: [
      'Strategy Browser: Discord export and import moved here — the natural home for community sharing',
      'Strategy Browser: "Share My Session" button — export preview with tag selector, one-click copy',
      'Strategy Browser: "Import" button — analyse any export at your current divine price',
      'Map Log: simplified back to pure map tracking — no export clutter',
      'Sessions panel: simplified — session management only, no import modal',
      'poe.ninja: removed dead getindexstate endpoint call — no more 404 console noise',
      'DevTools no longer open automatically in production builds',
    ],
  },
  {
    version: '1.0.6',
    date: '2026-04-14',
    changes: [
      // Strategy Browser
      'Strategy Browser: community strategy feed — browse builds posted by your group',
      'Strategy Browser: filter by build type (Delirium, Legion, Breach, etc.), min div/map, and sort',
      'Strategy Browser: "Load Build Settings" imports scarabs, chisel, and atlas tree in one click',
      'Strategy Browser: "View in Discord" button links directly to the source message for voting',
      'Strategy Browser: strategy scores via 👍/👎 Discord reactions — sort by Top Rated',
      'Strategy Browser: regex displayed with one-click copy buttons',

      // Discord export
      'Discord export: optional Build Type tag selector — overrides auto-detection from scarabs',
      'Discord export: tag appears in Strategy Browser and is filterable',

      // Atlas Tree
      'Atlas Tree: reloads automatically when "Load Build Settings" is used',
      'Atlas Tree: correctly persists per-session — load/new session always shows the right tree',

      // App polish
      'Map Analyzer: stash grid and legend centered',
      'Dashboard: stat box labels embedded in box, projected values larger',
      'Dashboard: loot list uses smart load-more (25 at a time)',
      'Dashboard: clearing loot now asks for confirmation',
      'Investment: cost badges centered, divine price box properly aligned',
      'Investment: Advanced Costs sections start collapsed',

      // Data fixes
      'Scarab list: fully corrected against wiki — fixed typos, added 11 missing entries',
      'Atlas Calc: "Uncharted Realms" corrected to "Multiplying Modifiers"',
      'Content Security Policy: HTTP strategy servers now work alongside HTTPS',
    ],
  },
  {
    version: '1.0.4',
    date: '2026-04-14',
    changes: [
      'Atlas Tree: tree persists per-session and resets on new session',
      'Dashboard: stat boxes redesigned — labels inside, larger projected values',
      'Dashboard: loot smart load-more, clear confirmation, loot fills remaining space',
      'Investment: cost badges centered, divine price box aligned',
      'Investment: Advanced Costs sections start collapsed',
      'Map Analyzer: layout dropdown (Map Tab / Regular / Quad / Map Device)',
      'Map Analyzer: stash grid centered',
      'Atlas Calc: wizard resets correctly on session change, pill edit goes back to single question',
      'Scarab list: corrected against wiki, 11 missing entries added',
      'Atlas Calc: "Uncharted Realms" → "Multiplying Modifiers"',
      'Auto-updater: public repo, background checks working',
    ],
  },
  {
    version: '1.0.1',
    date: '2026-04-13',
    changes: [
      'Merged Statistics + Loot into a single Dashboard panel with collapsible sections',
      'Advanced Costs modal: scrollable, all sections always accessible',
      'Investment: divine price and rolling cost in a boxed layout',
      'Investment: collapsible cost sections, active costs shown as clickable badges',
      'Atlas Calc: step-by-step wizard for first-time setup; compact pill view after',
      'Atlas Tree: URL saves on every navigation, included in Discord export',
      'Discord export: readable markdown format, imports from both raw and rendered',
      'Scarab clear (×) button inside the autocomplete field — no layout shift',
      'Split session: price-per-split field, auto-counts from parsed maps',
      'Chisel: Cartographer added, bonus correctly shows +10% Quantity',
      'App title renamed to WraeclastLedger throughout',
      'Installer now prompts for installation directory',
      'Check for Updates button in toolbar',
    ],
  },
  {
    version: '1.0.0',
    date: '2026-04-11',
    changes: [
      'Initial release',
      'Map Log with live clipboard capture (Ctrl+C in-game)',
      'Atlas Calc: multiplier from fragments, nodes, and mounting bonuses',
      'Investment panel: scarabs, chisel, delirium orbs, astrolabes, split session',
      'Statistics: base → projected with chisel and quality awareness',
      'Loot tracker: baseline / return CSV diff view with category breakdown',
      'Regex generator with trimmed mean (run / slam filters)',
      'Map Analyzer: stash grid + paste analyzer for T16.5 Originator maps',
      'Atlas Tree viewer via pathofpathing.com',
      'Session save, load, rename, delete',
      'Discord export and import (markdown format)',
      'Auto-update via GitHub Releases',
    ],
  },
];
